-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Tree.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open milhouse

/-- [core::borrow::{impl core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::hash::impls::{impl core::hash::Hash for usize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<usize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<usize>}::hash"]
axiom Usize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Usize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for (T, B)}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 893:20-893:60
    Name pattern: [core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash"]
axiom Pair.Insts.CoreHashHash.hash
  {T : Type} {B : Type} {S : Type} (HashInst : core.hash.Hash T) (HashInst1 :
  core.hash.Hash B) (HasherInst : core.hash.Hasher S) :
  (T × B) → S → Result S

/-- [core::mem::size_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 373:0-373:34
    Name pattern: [core::mem::size_of]
    Visibility: public -/
@[rust_fun "core::mem::size_of"]
axiom core.mem.size_of (T : Type) : Result Std.Usize

/-- [core::num::{usize}::trailing_zeros]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 177:8-177:48
    Name pattern: [core::num::{usize}::trailing_zeros]
    Visibility: public -/
@[rust_fun "core::num::{usize}::trailing_zeros"]
axiom core.num.Usize.trailing_zeros : Std.Usize → Result Std.U32

/-- [core::num::{usize}::checked_next_power_of_two]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3924:8-3924:68
    Name pattern: [core::num::{usize}::checked_next_power_of_two]
    Visibility: public -/
@[rust_fun "core::num::{usize}::checked_next_power_of_two"]
axiom core.num.Usize.checked_next_power_of_two
  : Std.Usize → Result (Option Std.Usize)

/-- [core::option::{core::option::Option<T>}::is_none_or]:
    Source: '/rustc/library/core/src/option.rs', lines 707:4-707:95
    Name pattern: [core::option::{core::option::Option<@T>}::is_none_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_none_or"]
axiom core.option.Option.is_none_or
  {T : Type} {T1 : Type} (opsfunctionFnOnceT1TupleTBoolInst :
  core.ops.function.FnOnce T1 T Bool) :
  Option T → T1 → Result Bool

/-- [core::option::{core::option::Option<T>}::unwrap_or_default]:
    Source: '/rustc/library/core/src/option.rs', lines 1090:4-1092:27
    Name pattern: [core::option::{core::option::Option<@T>}::unwrap_or_default]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::unwrap_or_default"]
axiom core.option.Option.unwrap_or_default
  {T : Type} (defaultDefaultInst : core.default.Default T) :
  Option T → Result T

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
axiom core.option.Option.ok_or
  {T : Type} {E : Type} : Option T → E → Result (core.result.Result T E)

/-- [core::option::{core::option::Option<(T, U)>}::unzip]:
    Source: '/rustc/library/core/src/option.rs', lines 2111:4-2111:48
    Name pattern: [core::option::{core::option::Option<(@T, @U)>}::unzip]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<(@T, @U)>}::unzip"]
axiom core.option.OptionPair.unzip
  {T : Type} {U : Type} : Option (T × U) → Result ((Option T) × (Option U))

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    Source: '/rustc/library/core/src/option.rs', lines 2135:4-2137:16
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::copied]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
axiom core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T)

/-- [core::option::{core::option::Option<&'_0 T>}::cloned]:
    Source: '/rustc/library/core/src/option.rs', lines 2161:4-2163:17
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::cloned]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::cloned"]
axiom core.option.OptionShared0T.cloned
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}::partial_cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 69:16-69:76
    Name pattern: [core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp"]
axiom Pair.Insts.CoreCmpPartialOrdPair.partial_cmp
  {U : Type} {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd U U)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  (U × T) → (U × T) → Result (Option Ordering)

/-- [core::tuple::{impl core::cmp::Ord for (U, T)}::cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 114:16-114:60
    Name pattern: [core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp"]
axiom Pair.Insts.CoreCmpOrd.cmp
  {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U) (cmpOrdInst1 :
  core.cmp.Ord T) :
  (U × T) → (U × T) → Result Ordering

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1035:4-1038:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get"]
axiom std.collections.hash.map.HashMap.get
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option V)

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1333:4-1333:53
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert"]
axiom std.collections.hash.map.HashMap.insert
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.map.HashMap K V S A → K → V → Result ((Option V)
    × (std.collections.hash.map.HashMap K V S A))

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::finish]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 140:4-140:27
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  : std.hash.random.DefaultHasher → Result Std.U64

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::write]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 130:4-130:35
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
  :
  std.hash.random.DefaultHasher → Slice Std.U8 → Result
    std.hash.random.DefaultHasher

/-- [std::hash::random::{impl core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}::build_hasher]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 83:4-83:43
    Name pattern: [std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher"]
axiom
  std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
  : std.hash.random.RandomState → Result std.hash.random.DefaultHasher

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, A>}::get]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 717:4-720:15
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get"]
axiom alloc.collections.btree.map.BTreeMap.get
  {K : Type} {V : Type} {A : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone A) (coreborrowBorrowInst : core.borrow.Borrow K Q)
  (corecmpOrdInst : core.cmp.Ord K) (corecmpOrdInst1 : core.cmp.Ord Q) :
  alloc.collections.btree.map.BTreeMap K V A → Q → Result (Option V)

/-- [alloy_primitives::bits::fixed::{impl core::clone::Clone for alloy_primitives::bits::fixed::FixedBytes<N>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 16:4-16:9
    Name pattern: [alloy_primitives::bits::fixed::{core::clone::Clone<alloy_primitives::bits::fixed::FixedBytes<@N>>}::clone]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::clone::Clone<alloy_primitives::bits::fixed::FixedBytes<@N>>}::clone"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCloneClone.clone
  {N : Std.Usize} :
  alloy_primitives.bits.fixed.FixedBytes N → Result
    (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{impl core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<N>> for alloy_primitives::bits::fixed::FixedBytes<N>}::eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 18:4-18:13
    Name pattern: [alloy_primitives::bits::fixed::{core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>}::eq]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>}::eq"]
axiom
  alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes.eq
  {N : Std.Usize} :
  alloy_primitives.bits.fixed.FixedBytes N →
    alloy_primitives.bits.fixed.FixedBytes N → Result Bool

/-- [alloy_primitives::bits::fixed::{impl core::cmp::Eq for alloy_primitives::bits::fixed::FixedBytes<N>}::assert_fields_are_eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 19:4-19:6
    Name pattern: [alloy_primitives::bits::fixed::{core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>}::assert_fields_are_eq]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>}::assert_fields_are_eq"]
axiom
  alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq.assert_fields_are_eq
  {N : Std.Usize} : alloy_primitives.bits.fixed.FixedBytes N → Result Unit

/-- [alloy_primitives::bits::fixed::{impl core::hash::Hash for alloy_primitives::bits::fixed::FixedBytes<N>}::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 22:4-22:8
    Name pattern: [alloy_primitives::bits::fixed::{core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>}::hash]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>}::hash"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash.hash
  {__H : Type} {N : Std.Usize} (corehashHasherInst : core.hash.Hasher __H) :
  alloy_primitives.bits.fixed.FixedBytes N → __H → Result __H

/-- [alloy_primitives::bits::fixed::{impl core::default::Default for alloy_primitives::bits::fixed::FixedBytes<N>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 41:4-41:24
    Name pattern: [alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
  (N : Std.Usize) : Result (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 337:4-337:24
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO]
    Visibility: public -/
@[rust_const
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO"]
axiom alloy_primitives.bits.fixed.FixedBytes.ZERO (N : Std.Usize)
  : Result (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::is_zero]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 581:4-581:33
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::is_zero]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::is_zero"]
axiom alloy_primitives.bits.fixed.FixedBytes.is_zero
  {N : Std.Usize} : alloy_primitives.bits.fixed.FixedBytes N → Result Bool

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 371:4-371:44
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::new]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::new"]
axiom lock_api.rwlock.RwLock.new
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  T → Result (lock_api.rwlock.RwLock R T)

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::read]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 467:4-467:51
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::read]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::read"]
axiom lock_api.rwlock.RwLock.read
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLock R T → Result (lock_api.rwlock.RwLockReadGuard R T
    Clause0_GuardMarker)

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::get_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 527:4-527:39
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::get_mut]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::get_mut"]
axiom lock_api.rwlock.RwLock.get_mut
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLock R T → Result (T × (T → lock_api.rwlock.RwLock R
    T))

/-- [lock_api::rwlock::{impl core::ops::deref::Deref<T> for lock_api::rwlock::RwLockReadGuard<'a, R, T, Clause0_GuardMarker>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 1365:4-1365:25
    Name pattern: [lock_api::rwlock::{core::ops::deref::Deref<lock_api::rwlock::RwLockReadGuard<'a, @R, @T, @Clause0_GuardMarker>, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "lock_api::rwlock::{core::ops::deref::Deref<lock_api::rwlock::RwLockReadGuard<'a, @R, @T, @Clause0_GuardMarker>, @T>}::deref"]
axiom lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLockReadGuard R T Clause0_GuardMarker → Result T

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::unlock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 129:4-129:34
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::try_lock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 116:4-116:37
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Bool

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::lock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 107:4-107:25
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::unlock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 94:4-94:37
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::try_lock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 80:4-80:40
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Bool

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::lock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 67:4-67:28
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::INIT]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 60:4-60:25
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::INIT]
    Visibility: public -/
@[rust_const
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::INIT"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.INIT
  : Result parking_lot.raw_rwlock.RawRwLock

/-- [triomphe::arc::{triomphe::arc::Arc<T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 80:4-80:31
    Name pattern: [triomphe::arc::{triomphe::arc::Arc<@T>}::new]
    Visibility: public -/
@[rust_fun "triomphe::arc::{triomphe::arc::Arc<@T>}::new"]
axiom triomphe.arc.Arc.new {T : Type} : T → Result (triomphe.arc.Arc T)

/-- [triomphe::arc::{triomphe::arc::Arc<T>}::ptr_eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 281:4-281:52
    Name pattern: [triomphe::arc::{triomphe::arc::Arc<@T>}::ptr_eq]
    Visibility: public -/
@[rust_fun "triomphe::arc::{triomphe::arc::Arc<@T>}::ptr_eq"]
axiom triomphe.arc.Arc.ptr_eq
  {T : Type} : triomphe.arc.Arc T → triomphe.arc.Arc T → Result Bool

/-- [triomphe::arc::{impl core::clone::Clone for triomphe::arc::Arc<T>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 450:4-450:27
    Name pattern: [triomphe::arc::{core::clone::Clone<triomphe::arc::Arc<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::clone::Clone<triomphe::arc::Arc<@T>>}::clone"]
axiom triomphe.arc.Arc.Insts.CoreCloneClone.clone
  {T : Type} : triomphe.arc.Arc T → Result (triomphe.arc.Arc T)

/-- [triomphe::arc::{impl core::ops::deref::Deref<T> for triomphe::arc::Arc<T>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 490:4-490:25
    Name pattern: [triomphe::arc::{core::ops::deref::Deref<triomphe::arc::Arc<@T>, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::ops::deref::Deref<triomphe::arc::Arc<@T>, @T>}::deref"]
axiom triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref
  {T : Type} : triomphe.arc.Arc T → Result T

/-- [triomphe::arc::{impl core::cmp::PartialEq<triomphe::arc::Arc<T>> for triomphe::arc::Arc<T>}::eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 667:4-667:40
    Name pattern: [triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::eq"]
axiom triomphe.arc.Arc.Insts.CoreCmpPartialEqArc.eq
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  triomphe.arc.Arc T → triomphe.arc.Arc T → Result Bool

