-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: function definitions
import Aeneas
import Tree.Types
import Tree.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace milhouse

/-- Trait implementation: [core::borrow::{impl core::borrow::Borrow<T> for T}]
    Source: '/rustc/library/core/src/borrow.rs', lines 212:0-212:37
    Name pattern: [core::borrow::Borrow<@T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<@T, @T>"]
def core.borrow.Borrow.Blanket (T : Type) : core.borrow.Borrow T T := {
  borrow := core.borrow.Borrow.Blanket.borrow
}

/-- Trait implementation: [core::hash::impls::{impl core::hash::Hash for usize}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 810:12-810:29
    Name pattern: [core::hash::Hash<usize>] -/
@[reducible, rust_trait_impl "core::hash::Hash<usize>"]
def Usize.Insts.CoreHashHash : core.hash.Hash Std.Usize := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    Usize.Insts.CoreHashHash.hash HasherInst
}

/-- Trait implementation: [core::hash::impls::{impl core::hash::Hash for (T, B)}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 890:16-890:60
    Name pattern: [core::hash::Hash<(@T, @B)>] -/
@[reducible, rust_trait_impl "core::hash::Hash<(@T, @B)>"]
def Pair.Insts.CoreHashHash {T : Type} {B : Type} (HashInst : core.hash.Hash T)
  (HashInst1 : core.hash.Hash B) : core.hash.Hash (T × B) := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    Pair.Insts.CoreHashHash.hash HashInst HashInst1 HasherInst
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::Eq for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 44:12-44:60
    Name pattern: [core::cmp::Eq<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<(@U, @T)>"]
def Pair.Insts.CoreCmpEq {U : Type} {T : Type} (cmpEqInst : core.cmp.Eq U)
  (cmpEqInst1 : core.cmp.Eq T) : core.cmp.Eq (U × T) := {
  partialEqInst := Pair.Insts.CoreCmpPartialEqPair cmpEqInst.partialEqInst
    cmpEqInst1.partialEqInst
  assert_fields_are_eq := fun _ => ok ()
}

/-- Trait implementation: [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 125:0-125:29
    Name pattern: [core::hash::Hasher<std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::Hasher<std::hash::random::DefaultHasher>"]
def std.hash.random.DefaultHasher.Insts.CoreHashHasher : core.hash.Hasher
  std.hash.random.DefaultHasher := {
  finish := std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  write := std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
}

/-- Trait implementation: [std::hash::random::{impl core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 80:0-80:32
    Name pattern: [core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>"]
def std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher :
  core.hash.BuildHasher std.hash.random.RandomState
  std.hash.random.DefaultHasher := {
  HasherInst := std.hash.random.DefaultHasher.Insts.CoreHashHasher
  build_hasher :=
    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
}

/-- Trait implementation: [alloy_primitives::bits::fixed::{impl core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<N>> for alloy_primitives::bits::fixed::FixedBytes<N>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 18:4-18:13
    Name pattern: [core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>"]
def alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes (N
  : Std.Usize) : core.cmp.PartialEq (alloy_primitives.bits.fixed.FixedBytes N)
  (alloy_primitives.bits.fixed.FixedBytes N) := {
  eq :=
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes.eq
}

/-- Trait implementation: [alloy_primitives::bits::fixed::{impl core::cmp::Eq for alloy_primitives::bits::fixed::FixedBytes<N>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 19:4-19:6
    Name pattern: [core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>] -/
@[reducible, rust_trait_impl
  "core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>"]
def alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq (N : Std.Usize) :
  core.cmp.Eq (alloy_primitives.bits.fixed.FixedBytes N) := {
  partialEqInst :=
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes N
  assert_fields_are_eq :=
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- Trait implementation: [alloy_primitives::bits::fixed::{impl core::hash::Hash for alloy_primitives::bits::fixed::FixedBytes<N>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 22:4-22:8
    Name pattern: [core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>] -/
@[reducible, rust_trait_impl
  "core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>"]
def alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash (N : Std.Usize) :
  core.hash.Hash (alloy_primitives.bits.fixed.FixedBytes N) := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash.hash
    corehashHasherInst
}

/-- Trait implementation: [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 59:0-59:45
    Name pattern: [lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>] -/
@[reducible, rust_trait_impl
  "lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>"]
def parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend :
  lock_api.rwlock.RawRwLock parking_lot.raw_rwlock.RawRwLock
  lock_api.GuardNoSend := {
  INIT :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.INIT
  lock_shared :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_shared
  try_lock_shared :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_shared
  unlock_shared :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_shared
  lock_exclusive :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_exclusive
  try_lock_exclusive :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_exclusive
  unlock_exclusive :=
    parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_exclusive
}

/-- [milhouse::leaf::{impl core::clone::Clone for milhouse::leaf::Leaf<T>}::clone]:
    Source: 'src/leaf.rs', lines 21:4-26:5
    Visibility: public -/
def leaf.Leaf.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (self : leaf.Leaf T) :
  Result (leaf.Leaf T)
  := do
  let rlrg ←
    lock_api.rwlock.RwLock.read
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      self.hash
  let fb ←
    lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      rlrg
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      fb
  let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone self.value
  ok { hash := rl, value := a }

/-- [milhouse::leaf::{milhouse::leaf::Leaf<T>}::with_hash]:
    Source: 'src/leaf.rs', lines 34:4-39:5
    Visibility: public -/
def leaf.Leaf.with_hash
  {T : Type} (value : T)
  (hash : alloy_primitives.bits.fixed.FixedBytes 32#usize) :
  Result (leaf.Leaf T)
  := do
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      hash
  let a ← triomphe.arc.Arc.new value
  ok { hash := rl, value := a }

/-- [milhouse::leaf::{milhouse::leaf::Leaf<T>}::new]:
    Source: 'src/leaf.rs', lines 30:4-32:5
    Visibility: public -/
def leaf.Leaf.new {T : Type} (value : T) : Result (leaf.Leaf T) := do
  let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
  leaf.Leaf.with_hash value fb

/-- [milhouse::packed_leaf::{impl core::clone::Clone for milhouse::packed_leaf::PackedLeaf<T>}::clone]:
    Source: 'src/packed_leaf.rs', lines 21:4-26:5
    Visibility: public -/
def packed_leaf.PackedLeaf.Insts.CoreCloneClone.clone
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) (corecloneCloneInst
  : core.clone.Clone T) (self : packed_leaf.PackedLeaf T) :
  Result (packed_leaf.PackedLeaf T)
  := do
  let rlrg ←
    lock_api.rwlock.RwLock.read
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      self.hash
  let fb ←
    lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      rlrg
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      fb
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.values
  ok { hash := rl, values := v }

/-- [milhouse::packed_leaf::{milhouse::packed_leaf::PackedLeaf<T>}::single]:
    Source: 'src/packed_leaf.rs', lines 58:4-66:5
    Visibility: public -/
def packed_leaf.PackedLeaf.single
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) (corecloneCloneInst
  : core.clone.Clone T) (value : T) :
  Result (packed_leaf.PackedLeaf T)
  := do
  let i ← tree_hashTreeHashInst.tree_hash_packing_factor
  let values := alloc.vec.Vec.with_capacity T i
  let values1 ← alloc.vec.Vec.push values value
  let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      fb
  ok { hash := rl, values := values1 }

/-- [milhouse::packed_leaf::{milhouse::packed_leaf::PackedLeaf<T>}::insert_mut]:
    Source: 'src/packed_leaf.rs', lines 106:4-121:5
    Visibility: public -/
def packed_leaf.PackedLeaf.insert_mut
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) (corecloneCloneInst
  : core.clone.Clone T) (self : packed_leaf.PackedLeaf T)
  (sub_index : Std.Usize) (value : T) :
  Result ((core.result.Result Unit error.Error) × (packed_leaf.PackedLeaf T))
  := do
  let (_, get_mut_back) ←
    lock_api.rwlock.RwLock.get_mut
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      self.hash
  let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
  let i := alloc.vec.Vec.len self.values
  if sub_index = i
  then
    let v ← alloc.vec.Vec.push self.values value
    let rl := get_mut_back fb
    ok (core.result.Result.Ok (), { hash := rl, values := v })
  else
    let i1 := alloc.vec.Vec.len self.values
    if sub_index < i1
    then
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice T)
          self.values sub_index
      let rl := get_mut_back fb
      let v := index_mut_back value
      ok (core.result.Result.Ok (), { hash := rl, values := v })
    else
      let i2 := alloc.vec.Vec.len self.values
      let rl := get_mut_back fb
      ok (core.result.Result.Err (error.Error.PackedLeafOutOfBounds sub_index
        i2), { self with hash := rl })

/-- [milhouse::packed_leaf::{milhouse::packed_leaf::PackedLeaf<T>}::insert_at_index]:
    Source: 'src/packed_leaf.rs', lines 76:4-84:5
    Visibility: public -/
def packed_leaf.PackedLeaf.insert_at_index
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) (corecloneCloneInst
  : core.clone.Clone T) (self : packed_leaf.PackedLeaf T) (index : Std.Usize)
  (value : T) :
  Result (core.result.Result (packed_leaf.PackedLeaf T) error.Error)
  := do
  let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      fb
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.values
  let i ← tree_hashTreeHashInst.tree_hash_packing_factor
  let sub_index ← index % i
  let (r, updated) ←
    packed_leaf.PackedLeaf.insert_mut tree_hashTreeHashInst corecloneCloneInst
      { hash := rl, values := v } sub_index value
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    ok (core.result.Result.Ok updated)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (packed_leaf.PackedLeaf T) (core.convert.FromSame error.Error) residual

/-- [milhouse::tree::{impl core::hash::Hash for milhouse::tree::Tree<T>}::hash]:
    Source: 'src/tree.rs', lines 11:16-11:21
    Visibility: public -/
def tree.Tree.Insts.CoreHashHash.hash
  {T : Type} {H : Type} (ValueInst : Value T) (corehashHashLeafInst :
  core.hash.Hash (leaf.Leaf T)) (corehashHashPackedLeafInst : core.hash.Hash
  (packed_leaf.PackedLeaf T)) (corehashHashArcTreeInst : core.hash.Hash
  (triomphe.arc.Arc (tree.Tree T))) (corehashHashUsizeInst : core.hash.Hash
  Std.Usize) (corehashHasherInst : core.hash.Hasher H) (self : tree.Tree T)
  (state : H) :
  Result H
  := do
  match self with
  | tree.Tree.Leaf _0 =>
    let state1 ←
      Usize.Insts.CoreHashHash.hash corehashHasherInst 0#usize state
    corehashHashLeafInst.hash corehashHasherInst _0 state1
  | tree.Tree.PackedLeaf _0 =>
    let state1 ←
      Usize.Insts.CoreHashHash.hash corehashHasherInst 1#usize state
    corehashHashPackedLeafInst.hash corehashHasherInst _0 state1
  | tree.Tree.Node _ v_left v_right =>
    let state1 ←
      Usize.Insts.CoreHashHash.hash corehashHasherInst 2#usize state
    let state2 ←
      corehashHashArcTreeInst.hash corehashHasherInst v_left state1
    corehashHashArcTreeInst.hash corehashHasherInst v_right state2
  | tree.Tree.Zero _0 =>
    let state1 ←
      Usize.Insts.CoreHashHash.hash corehashHasherInst 3#usize state
    Usize.Insts.CoreHashHash.hash corehashHasherInst _0 state1

/-- Trait implementation: [milhouse::tree::{impl core::hash::Hash for milhouse::tree::Tree<T>}]
    Source: 'src/tree.rs', lines 11:16-11:21 -/
@[reducible]
def tree.Tree.Insts.CoreHashHash {T : Type} (ValueInst : Value T)
  (corehashHashLeafInst : core.hash.Hash (leaf.Leaf T))
  (corehashHashPackedLeafInst : core.hash.Hash (packed_leaf.PackedLeaf T))
  (corehashHashArcTreeInst : core.hash.Hash (triomphe.arc.Arc (tree.Tree T)))
  (corehashHashUsizeInst : core.hash.Hash Std.Usize) : core.hash.Hash
  (tree.Tree T) := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    tree.Tree.Insts.CoreHashHash.hash ValueInst corehashHashLeafInst
    corehashHashPackedLeafInst corehashHashArcTreeInst Usize.Insts.CoreHashHash
    corehashHasherInst
}

/-- [milhouse::tree::{impl core::clone::Clone for milhouse::tree::Tree<T>}::clone]:
    Source: 'src/tree.rs', lines 30:4-41:5
    Visibility: public -/
def tree.Tree.Insts.CoreCloneClone.clone
  {T : Type} (ValueInst : Value T) (self : tree.Tree T) :
  Result (tree.Tree T)
  := do
  match self with
  | tree.Tree.Leaf l =>
    let l1 ←
      leaf.Leaf.Insts.CoreCloneClone.clone ValueInst.corecloneCloneInst l
    ok (tree.Tree.Leaf l1)
  | tree.Tree.PackedLeaf pl =>
    let pl1 ←
      packed_leaf.PackedLeaf.Insts.CoreCloneClone.clone
        ValueInst.tree_hashTreeHashInst ValueInst.corecloneCloneInst pl
    ok (tree.Tree.PackedLeaf pl1)
  | tree.Tree.Node hash left right =>
    let rlrg ←
      lock_api.rwlock.RwLock.read
        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
        hash
    let fb ←
      lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
        rlrg
    let rl ←
      lock_api.rwlock.RwLock.new
        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
        fb
    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone left
    let a1 ← triomphe.arc.Arc.Insts.CoreCloneClone.clone right
    ok (tree.Tree.Node rl a a1)
  | tree.Tree.Zero _ => ok self

/-- Trait implementation: [milhouse::tree::{impl core::clone::Clone for milhouse::tree::Tree<T>}]
    Source: 'src/tree.rs', lines 29:0-42:1 -/
@[reducible]
def tree.Tree.Insts.CoreCloneClone {T : Type} (ValueInst : Value T) :
  core.clone.Clone (tree.Tree T) := {
  clone := tree.Tree.Insts.CoreCloneClone.clone ValueInst
}

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::zero]:
    Source: 'src/tree.rs', lines 57:4-59:5
    Visibility: public -/
def tree.Tree.zero
  {T : Type} (ValueInst : Value T) (depth : Std.Usize) :
  Result (triomphe.arc.Arc (tree.Tree T))
  := do
  triomphe.arc.Arc.new (tree.Tree.Zero depth)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::empty]:
    Source: 'src/tree.rs', lines 45:4-47:5
    Visibility: public -/
def tree.Tree.empty
  {T : Type} (ValueInst : Value T) (depth : Std.Usize) :
  Result (triomphe.arc.Arc (tree.Tree T))
  := do
  tree.Tree.zero ValueInst depth

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::node]:
    Source: 'src/tree.rs', lines 49:4-55:5
    Visibility: public -/
def tree.Tree.node
  {T : Type} (ValueInst : Value T) (left : triomphe.arc.Arc (tree.Tree T))
  (right : triomphe.arc.Arc (tree.Tree T))
  (hash : alloy_primitives.bits.fixed.FixedBytes 32#usize) :
  Result (triomphe.arc.Arc (tree.Tree T))
  := do
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      hash
  triomphe.arc.Arc.new (tree.Tree.Node rl left right)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::leaf]:
    Source: 'src/tree.rs', lines 61:4-63:5
    Visibility: public -/
def tree.Tree.leaf
  {T : Type} (ValueInst : Value T) (value : T) :
  Result (triomphe.arc.Arc (tree.Tree T))
  := do
  let l ← leaf.Leaf.new value
  triomphe.arc.Arc.new (tree.Tree.Leaf l)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::leaf_with_hash]:
    Source: 'src/tree.rs', lines 65:4-67:5
    Visibility: public -/
def tree.Tree.leaf_with_hash
  {T : Type} (ValueInst : Value T) (value : T)
  (hash : alloy_primitives.bits.fixed.FixedBytes 32#usize) :
  Result (triomphe.arc.Arc (tree.Tree T))
  := do
  let l ← leaf.Leaf.with_hash value hash
  triomphe.arc.Arc.new (tree.Tree.Leaf l)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::node_unboxed]:
    Source: 'src/tree.rs', lines 69:4-75:5
    Visibility: public -/
def tree.Tree.node_unboxed
  {T : Type} (ValueInst : Value T) (left : triomphe.arc.Arc (tree.Tree T))
  (right : triomphe.arc.Arc (tree.Tree T)) :
  Result (tree.Tree T)
  := do
  let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
  let rl ←
    lock_api.rwlock.RwLock.new
      parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
      fb
  ok (tree.Tree.Node rl left right)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::zero_unboxed]:
    Source: 'src/tree.rs', lines 77:4-79:5
    Visibility: public -/
def tree.Tree.zero_unboxed
  {T : Type} (ValueInst : Value T) (depth : Std.Usize) :
  Result (tree.Tree T)
  := do
  ok (tree.Tree.Zero depth)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::leaf_unboxed]:
    Source: 'src/tree.rs', lines 81:4-83:5
    Visibility: public -/
def tree.Tree.leaf_unboxed
  {T : Type} (ValueInst : Value T) (value : T) : Result (tree.Tree T) := do
  let l ← leaf.Leaf.new value
  ok (tree.Tree.Leaf l)

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::get_recursive]:
    Source: 'src/tree.rs', lines 85:4-104:5
    Visibility: public -/
def tree.Tree.get_recursive
  {T : Type} (ValueInst : Value T) (self : tree.Tree T) (index : Std.Usize)
  (depth : Std.Usize) (packing_depth : Std.Usize) :
  Result (Option T)
  := do
  match self with
  | tree.Tree.Leaf l =>
    if depth = 0#usize
    then
      let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref l.value
      ok (some t)
    else ok none
  | tree.Tree.PackedLeaf pl =>
    if depth = 0#usize
    then
      let s := alloc.vec.Vec.deref pl.values
      let i ← ValueInst.tree_hashTreeHashInst.tree_hash_packing_factor
      let i1 ← index % i
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice T) s i1
    else ok none
  | tree.Tree.Node _ left right =>
    if depth > 0#usize
    then
      let new_depth ← depth - 1#usize
      let i ← new_depth + packing_depth
      let i1 ← index >>> i
      let i2 ← lift (i1 &&& 1#usize)
      if i2 = 0#usize
      then
        let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref left
        tree.Tree.get_recursive ValueInst t index new_depth packing_depth
      else
        let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref right
        tree.Tree.get_recursive ValueInst t index new_depth packing_depth
    else ok none
  | tree.Tree.Zero _ => ok none
partial_fixpoint

/-- [milhouse::utils::opt_packing_factor]:
    Source: 'src/utils.rs', lines 67:0-72:1
    Visibility: public -/
def utils.opt_packing_factor
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) :
  Result (Option Std.Usize)
  := do
  let tht ← tree_hashTreeHashInst.tree_hash_type
  match tht with
  | tree_hash.TreeHashType.Basic =>
    let i ← tree_hashTreeHashInst.tree_hash_packing_factor
    ok (some i)
  | tree_hash.TreeHashType.Vector => ok none
  | tree_hash.TreeHashType.List => ok none
  | tree_hash.TreeHashType.Container => ok none

/-- [milhouse::utils::int_log]:
    Source: 'src/utils.rs', lines 42:0-47:1
    Visibility: public -/
def utils.int_log (n : Std.Usize) : Result Std.Usize := do
  let o ← core.num.Usize.checked_next_power_of_two n
  match o with
  | none => let i ← core.mem.size_of Std.Usize
            8#usize * i
  | some x =>
    let i ← core.num.Usize.trailing_zeros x
    ok (UScalar.cast .Usize i)

/-- [milhouse::utils::opt_packing_depth]:
    Source: 'src/utils.rs', lines 75:0-78:1
    Visibility: public -/
def utils.opt_packing_depth
  {T : Type} (tree_hashTreeHashInst : tree_hash.TreeHash T) :
  Result (Option Std.Usize)
  := do
  let o ← utils.opt_packing_factor tree_hashTreeHashInst
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← utils.int_log val
    ok (some i)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.Usize residual

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::with_updated_leaf]:
    Source: 'src/tree.rs', lines 109:4-156:5
    Visibility: public -/
def tree.Tree.with_updated_leaf
  {T : Type} (ValueInst : Value T) (self : tree.Tree T) (index : Std.Usize)
  (new_value : T) (depth : Std.Usize) :
  Result (core.result.Result (triomphe.arc.Arc (tree.Tree T)) error.Error)
  := do
  match self with
  | tree.Tree.Leaf _ =>
    if depth = 0#usize
    then
      let a ← tree.Tree.leaf ValueInst new_value
      ok (core.result.Result.Ok a)
    else ok (core.result.Result.Err error.Error.UpdateLeafError)
  | tree.Tree.PackedLeaf leaf =>
    if depth = 0#usize
    then
      let r ←
        packed_leaf.PackedLeaf.insert_at_index ValueInst.tree_hashTreeHashInst
          ValueInst.corecloneCloneInst leaf index new_value
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let a ← triomphe.arc.Arc.new (tree.Tree.PackedLeaf val)
        ok (core.result.Result.Ok a)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (triomphe.arc.Arc (tree.Tree T)) (core.convert.FromSame error.Error)
          residual
    else ok (core.result.Result.Err error.Error.UpdateLeafError)
  | tree.Tree.Node _ left right =>
    if depth > 0#usize
    then
      let o ← utils.opt_packing_depth ValueInst.tree_hashTreeHashInst
      let packing_depth ← lift (core.option.Option.unwrap_or o 0#usize)
      let new_depth ← depth - 1#usize
      let i ← new_depth + packing_depth
      let i1 ← index >>> i
      let i2 ← lift (i1 &&& 1#usize)
      if i2 = 0#usize
      then
        let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref left
        let r ←
          tree.Tree.with_updated_leaf ValueInst t index new_value new_depth
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone right
          let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
          let a1 ← tree.Tree.node ValueInst val a fb
          ok (core.result.Result.Ok a1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (triomphe.arc.Arc (tree.Tree T)) (core.convert.FromSame
            error.Error) residual
      else
        let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone left
        let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref right
        let r ←
          tree.Tree.with_updated_leaf ValueInst t index new_value new_depth
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
          let a1 ← tree.Tree.node ValueInst a val fb
          ok (core.result.Result.Ok a1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (triomphe.arc.Arc (tree.Tree T)) (core.convert.FromSame
            error.Error) residual
    else ok (core.result.Result.Err error.Error.UpdateLeafError)
  | tree.Tree.Zero zero_depth =>
    if zero_depth = depth
    then
      if depth = 0#usize
      then
        let o ← utils.opt_packing_factor ValueInst.tree_hashTreeHashInst
        let b := core.option.Option.is_some o
        if b
        then
          let pl ←
            packed_leaf.PackedLeaf.single ValueInst.tree_hashTreeHashInst
              ValueInst.corecloneCloneInst new_value
          let a ← triomphe.arc.Arc.new (tree.Tree.PackedLeaf pl)
          ok (core.result.Result.Ok a)
        else
          let a ← tree.Tree.leaf ValueInst new_value
          ok (core.result.Result.Ok a)
      else
        let i ← depth - 1#usize
        let new_zero ← tree.Tree.zero ValueInst i
        let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone new_zero
        let fb ← alloy_primitives.bits.fixed.FixedBytes.ZERO 32#usize
        let a1 ← tree.Tree.node ValueInst a new_zero fb
        let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref a1
        tree.Tree.with_updated_leaf ValueInst t index new_value depth
    else ok (core.result.Result.Err error.Error.UpdateLeafError)
partial_fixpoint

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::compute_len]:
    Source: 'src/tree.rs', lines 243:4-250:5
    Visibility: public -/
def tree.Tree.compute_len
  {T : Type} (ValueInst : Value T) (self : tree.Tree T) :
  Result Std.Usize
  := do
  match self with
  | tree.Tree.Leaf _ => ok 1#usize
  | tree.Tree.PackedLeaf leaf => ok (alloc.vec.Vec.len leaf.values)
  | tree.Tree.Node _ left right =>
    let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref left
    let i ← tree.Tree.compute_len ValueInst t
    let t1 ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref right
    let i1 ← tree.Tree.compute_len ValueInst t1
    i + i1
  | tree.Tree.Zero _ => ok 0#usize
partial_fixpoint

/-- [milhouse::utils::{milhouse::utils::Length}::as_usize]:
    Source: 'src/utils.rs', lines 34:4-36:5
    Visibility: public -/
def utils.Length.as_usize (self : utils.Length) : Result Std.Usize := do
  ok self

/-- [milhouse::utils::{impl core::cmp::Ord for milhouse::utils::Length}::cmp]:
    Source: 'src/utils.rs', lines 23:43-23:46
    Visibility: public -/
def utils.Length.Insts.CoreCmpOrd.cmp
  (self : utils.Length) (other : utils.Length) : Result Ordering := do
  ok (core.cmp.impls.OrdUsize.cmp self other)

/-- [milhouse::utils::{impl core::cmp::PartialOrd<milhouse::utils::Length> for milhouse::utils::Length}::partial_cmp]:
    Source: 'src/utils.rs', lines 23:31-23:41
    Visibility: public -/
def utils.Length.Insts.CoreCmpPartialOrdLength.partial_cmp
  (self : utils.Length) (other : utils.Length) : Result (Option Ordering) := do
  let o ← utils.Length.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- [milhouse::utils::{impl core::cmp::PartialEq<milhouse::utils::Length> for milhouse::utils::Length}::eq]:
    Source: 'src/utils.rs', lines 23:16-23:25
    Visibility: public -/
def utils.Length.Insts.CoreCmpPartialEqLength.eq
  (self : utils.Length) (other : utils.Length) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [milhouse::utils::{impl core::cmp::PartialEq<milhouse::utils::Length> for milhouse::utils::Length}]
    Source: 'src/utils.rs', lines 23:16-23:25 -/
@[reducible]
def utils.Length.Insts.CoreCmpPartialEqLength : core.cmp.PartialEq utils.Length
  utils.Length := {
  eq := utils.Length.Insts.CoreCmpPartialEqLength.eq
}

/-- Trait implementation: [milhouse::utils::{impl core::cmp::PartialOrd<milhouse::utils::Length> for milhouse::utils::Length}]
    Source: 'src/utils.rs', lines 23:31-23:41 -/
@[reducible]
def utils.Length.Insts.CoreCmpPartialOrdLength : core.cmp.PartialOrd
  utils.Length utils.Length := {
  partialEqInst := utils.Length.Insts.CoreCmpPartialEqLength
  partial_cmp := utils.Length.Insts.CoreCmpPartialOrdLength.partial_cmp
}

/-- [milhouse::utils::{impl core::cmp::Eq for milhouse::utils::Length}::assert_fields_are_eq]:
    Source: 'src/utils.rs', lines 23:27-23:29
    Visibility: public -/
def utils.Length.Insts.CoreCmpEq.assert_fields_are_eq
  (self : utils.Length) : Result Unit := do
  ok ()

/-- Trait implementation: [milhouse::utils::{impl core::cmp::Eq for milhouse::utils::Length}]
    Source: 'src/utils.rs', lines 23:27-23:29 -/
@[reducible]
def utils.Length.Insts.CoreCmpEq : core.cmp.Eq utils.Length := {
  partialEqInst := utils.Length.Insts.CoreCmpPartialEqLength
  assert_fields_are_eq := utils.Length.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- Trait implementation: [milhouse::utils::{impl core::cmp::Ord for milhouse::utils::Length}]
    Source: 'src/utils.rs', lines 23:43-23:46 -/
@[reducible]
def utils.Length.Insts.CoreCmpOrd : core.cmp.Ord utils.Length := {
  eqInst := utils.Length.Insts.CoreCmpEq
  partialOrdInst := utils.Length.Insts.CoreCmpPartialOrdLength
  cmp := utils.Length.Insts.CoreCmpOrd.cmp
}

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::{impl core::ops::function::FnOnce<((milhouse::utils::Length, milhouse::utils::Length),), ((milhouse::utils::Length, milhouse::utils::Length), (milhouse::utils::Length, milhouse::utils::Length))> for milhouse::tree::{milhouse::tree::Tree<T>[TraitClause0]}::rebase_on::closure#1<'_0, T>}::call_once]:
    Source: 'src/tree.rs', lines 324:25-337:21 -/
def
  tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength.call_once
  {T : Type} (ValueInst : Value T) (c : tree.Tree.rebase_on.closure_1 T)
  (tupled_args : (utils.Length × utils.Length)) :
  Result ((utils.Length × utils.Length) × (utils.Length × utils.Length))
  := do
  let (orig_length, base_length) := tupled_args
  let i ← 1#usize <<< c
  let orig_left_length ←
    core.cmp.min utils.Length.Insts.CoreCmpOrd orig_length i
  let i1 ← utils.Length.as_usize orig_length
  let i2 ← utils.Length.as_usize orig_left_length
  let i3 ← i1 - i2
  let base_left_length ←
    core.cmp.min utils.Length.Insts.CoreCmpOrd base_length i
  let i4 ← utils.Length.as_usize base_length
  let i5 ← utils.Length.as_usize base_left_length
  let i6 ← i4 - i5
  ok ((orig_left_length, base_left_length), (i3, i6))

/-- Trait implementation: [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::{impl core::ops::function::FnOnce<((milhouse::utils::Length, milhouse::utils::Length),), ((milhouse::utils::Length, milhouse::utils::Length), (milhouse::utils::Length, milhouse::utils::Length))> for milhouse::tree::{milhouse::tree::Tree<T>[TraitClause0]}::rebase_on::closure#1<'_0, T>}]
    Source: 'src/tree.rs', lines 324:25-337:21 -/
@[reducible]
def
  tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength
  {T : Type} (ValueInst : Value T) : core.ops.function.FnOnce
  (tree.Tree.rebase_on.closure_1 T) (utils.Length × utils.Length)
  ((utils.Length × utils.Length) × (utils.Length × utils.Length)) := {
  call_once :=
    tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength.call_once
    ValueInst
}

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::{impl core::ops::function::FnOnce<((milhouse::utils::Length, milhouse::utils::Length),), bool> for milhouse::tree::{milhouse::tree::Tree<T>[TraitClause0]}::rebase_on::closure<T>}::call_once]:
    Source: 'src/tree.rs', lines 317:42-317:97 -/
def
  tree.Tree.rebase_on.closure.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthBool.call_once
  {T : Type} (ValueInst : Value T) (c : tree.Tree.rebase_on.closure T)
  (tupled_args : (utils.Length × utils.Length)) :
  Result Bool
  := do
  let (orig_length, base_length) := tupled_args
  utils.Length.Insts.CoreCmpPartialEqLength.eq orig_length base_length

/-- Trait implementation: [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::{impl core::ops::function::FnOnce<((milhouse::utils::Length, milhouse::utils::Length),), bool> for milhouse::tree::{milhouse::tree::Tree<T>[TraitClause0]}::rebase_on::closure<T>}]
    Source: 'src/tree.rs', lines 317:42-317:97 -/
@[reducible]
def
  tree.Tree.rebase_on.closure.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthBool
  {T : Type} (ValueInst : Value T) : core.ops.function.FnOnce
  (tree.Tree.rebase_on.closure T) (utils.Length × utils.Length) Bool := {
  call_once :=
    tree.Tree.rebase_on.closure.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthBool.call_once
    ValueInst
}

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on]:
    Source: 'src/tree.rs', lines 270:4-408:5
    Visibility: public -/
def tree.Tree.rebase_on
  {T : Type} (ValueInst : Value T) (orig : triomphe.arc.Arc (tree.Tree T))
  (base : triomphe.arc.Arc (tree.Tree T))
  (lengths : Option (utils.Length × utils.Length)) (full_depth : Std.Usize) :
  Result (core.result.Result (tree.RebaseAction (tree.Tree T)) error.Error)
  := do
  let b ← triomphe.arc.Arc.ptr_eq orig base
  if b
  then ok (core.result.Result.Ok tree.RebaseAction.EqualNoop)
  else
    let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref orig
    let t1 ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref base
    match t with
    | tree.Tree.Leaf l1 =>
      match t1 with
      | tree.Tree.Leaf l2 =>
        let b1 ←
          triomphe.arc.Arc.Insts.CoreCmpPartialEqArc.eq
            ValueInst.corecmpPartialEqInst l1.value l2.value
        if b1
        then ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace base))
        else ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
      | tree.Tree.PackedLeaf _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.Node _ _ _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.Zero _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
    | tree.Tree.PackedLeaf l1 =>
      match t1 with
      | tree.Tree.Leaf _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.PackedLeaf l2 =>
        let b1 ←
          alloc.vec.partial_eq.PartialEqVec.eq ValueInst.corecmpPartialEqInst
            l1.values l2.values
        if b1
        then ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace base))
        else ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
      | tree.Tree.Node _ _ _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.Zero _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
    | tree.Tree.Node orig_hash_lock l1 r1 =>
      match t1 with
      | tree.Tree.Leaf _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.PackedLeaf _ =>
        ok (core.result.Result.Err error.Error.InvalidRebaseLeaf)
      | tree.Tree.Node base_hash_lock l2 r2 =>
        if full_depth > 0#usize
        then
          let rlrg ←
            lock_api.rwlock.RwLock.read
              parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
              orig_hash_lock
          let orig_hash ←
            lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
              parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
              rlrg
          let rlrg1 ←
            lock_api.rwlock.RwLock.read
              parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
              base_hash_lock
          let base_hash ←
            lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
              parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
              rlrg1
          let b1 ← alloy_primitives.bits.fixed.FixedBytes.is_zero orig_hash
          if b1
          then
            let new_full_depth ← full_depth - 1#usize
            let o ←
              core.option.Option.map
                (tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength
                ValueInst) lengths new_full_depth
            let (left_lengths, right_lengths) ←
              core.option.OptionPair.unzip o
            let r ←
              tree.Tree.rebase_on ValueInst l1 l2 left_lengths new_full_depth
            let cf ← core.result.Result.Insts.CoreOpsTry.branch r
            match cf with
            | core.ops.control_flow.ControlFlow.Continue val =>
              let r3 ←
                tree.Tree.rebase_on ValueInst r1 r2 right_lengths
                  new_full_depth
              let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf1 with
              | core.ops.control_flow.ControlFlow.Continue val1 =>
                match val with
                | tree.RebaseAction.NotEqualNoop =>
                  match val1 with
                  | tree.RebaseAction.NotEqualNoop =>
                    ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                  | tree.RebaseAction.NotEqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.EqualNoop =>
                    ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                  | tree.RebaseAction.EqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                    let a1 ←
                      triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                    let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a2))
                | tree.RebaseAction.NotEqualReplace new_left =>
                  match val1 with
                  | tree.RebaseAction.NotEqualNoop =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.NotEqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl new_left
                        new_right)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a))
                  | tree.RebaseAction.EqualNoop =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.EqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ←
                      triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                | tree.RebaseAction.EqualNoop =>
                  match val1 with
                  | tree.RebaseAction.NotEqualNoop =>
                    ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                  | tree.RebaseAction.NotEqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.EqualNoop =>
                    ok (core.result.Result.Ok tree.RebaseAction.EqualNoop)
                  | tree.RebaseAction.EqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                    let a1 ←
                      triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                    let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a2))
                | tree.RebaseAction.EqualReplace new_left =>
                  match val1 with
                  | tree.RebaseAction.NotEqualNoop =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ←
                      triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                    let a1 ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                    let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a2))
                  | tree.RebaseAction.NotEqualReplace new_right =>
                    let rl ←
                      lock_api.rwlock.RwLock.new
                        parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                        orig_hash
                    let a ←
                      triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                    let a1 ←
                      triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                    ok (core.result.Result.Ok
                      (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.EqualNoop =>
                    ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace
                      base))
                  | tree.RebaseAction.EqualReplace _ =>
                    ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace
                      base))
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                  error.Error) residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                error.Error) residual
          else
            let b2 ←
              alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes.eq
                orig_hash base_hash
            if b2
            then
              let b3 ←
                core.option.Option.is_none_or
                  (tree.Tree.rebase_on.closure.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthBool
                  ValueInst) lengths ()
              if b3
              then
                ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace
                  base))
              else
                let new_full_depth ← full_depth - 1#usize
                let o ←
                  core.option.Option.map
                    (tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength
                    ValueInst) lengths new_full_depth
                let (left_lengths, right_lengths) ←
                  core.option.OptionPair.unzip o
                let r ←
                  tree.Tree.rebase_on ValueInst l1 l2 left_lengths
                    new_full_depth
                let cf ← core.result.Result.Insts.CoreOpsTry.branch r
                match cf with
                | core.ops.control_flow.ControlFlow.Continue val =>
                  let r3 ←
                    tree.Tree.rebase_on ValueInst r1 r2 right_lengths
                      new_full_depth
                  let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r3
                  match cf1 with
                  | core.ops.control_flow.ControlFlow.Continue val1 =>
                    match val with
                    | tree.RebaseAction.NotEqualNoop =>
                      match val1 with
                      | tree.RebaseAction.NotEqualNoop =>
                        ok (core.result.Result.Ok
                          tree.RebaseAction.NotEqualNoop)
                      | tree.RebaseAction.NotEqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                      | tree.RebaseAction.EqualNoop =>
                        ok (core.result.Result.Ok
                          tree.RebaseAction.NotEqualNoop)
                      | tree.RebaseAction.EqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                        let a1 ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                        let a2 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a2))
                    | tree.RebaseAction.NotEqualReplace new_left =>
                      match val1 with
                      | tree.RebaseAction.NotEqualNoop =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                      | tree.RebaseAction.NotEqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl new_left
                            new_right)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a))
                      | tree.RebaseAction.EqualNoop =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                      | tree.RebaseAction.EqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.EqualNoop =>
                      match val1 with
                      | tree.RebaseAction.NotEqualNoop =>
                        ok (core.result.Result.Ok
                          tree.RebaseAction.NotEqualNoop)
                      | tree.RebaseAction.NotEqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                      | tree.RebaseAction.EqualNoop =>
                        ok (core.result.Result.Ok tree.RebaseAction.EqualNoop)
                      | tree.RebaseAction.EqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                        let a1 ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                        let a2 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a2))
                    | tree.RebaseAction.EqualReplace new_left =>
                      match val1 with
                      | tree.RebaseAction.NotEqualNoop =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                        let a1 ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                        let a2 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a2))
                      | tree.RebaseAction.NotEqualReplace new_right =>
                        let rl ←
                          lock_api.rwlock.RwLock.new
                            parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                            orig_hash
                        let a ←
                          triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                        let a1 ←
                          triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.NotEqualReplace a1))
                      | tree.RebaseAction.EqualNoop =>
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.EqualReplace base))
                      | tree.RebaseAction.EqualReplace _ =>
                        ok (core.result.Result.Ok
                          (tree.RebaseAction.EqualReplace base))
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                      error.Error) residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                    error.Error) residual
            else
              let new_full_depth ← full_depth - 1#usize
              let o ←
                core.option.Option.map
                  (tree.Tree.rebase_on.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairLengthLengthPairPairLengthLengthPairLengthLength
                  ValueInst) lengths new_full_depth
              let (left_lengths, right_lengths) ←
                core.option.OptionPair.unzip o
              let r ←
                tree.Tree.rebase_on ValueInst l1 l2 left_lengths new_full_depth
              let cf ← core.result.Result.Insts.CoreOpsTry.branch r
              match cf with
              | core.ops.control_flow.ControlFlow.Continue val =>
                let r3 ←
                  tree.Tree.rebase_on ValueInst r1 r2 right_lengths
                    new_full_depth
                let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r3
                match cf1 with
                | core.ops.control_flow.ControlFlow.Continue val1 =>
                  match val with
                  | tree.RebaseAction.NotEqualNoop =>
                    match val1 with
                    | tree.RebaseAction.NotEqualNoop =>
                      ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                    | tree.RebaseAction.NotEqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.EqualNoop =>
                      ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                    | tree.RebaseAction.EqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                      let a1 ←
                        triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                      let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a2))
                  | tree.RebaseAction.NotEqualReplace new_left =>
                    match val1 with
                    | tree.RebaseAction.NotEqualNoop =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.NotEqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl new_left
                          new_right)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a))
                    | tree.RebaseAction.EqualNoop =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.EqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ←
                        triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl new_left a)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                  | tree.RebaseAction.EqualNoop =>
                    match val1 with
                    | tree.RebaseAction.NotEqualNoop =>
                      ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
                    | tree.RebaseAction.NotEqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.EqualNoop =>
                      ok (core.result.Result.Ok tree.RebaseAction.EqualNoop)
                    | tree.RebaseAction.EqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone l1
                      let a1 ←
                        triomphe.arc.Arc.Insts.CoreCloneClone.clone new_right
                      let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a2))
                  | tree.RebaseAction.EqualReplace new_left =>
                    match val1 with
                    | tree.RebaseAction.NotEqualNoop =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ←
                        triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                      let a1 ← triomphe.arc.Arc.Insts.CoreCloneClone.clone r1
                      let a2 ← triomphe.arc.Arc.new (tree.Tree.Node rl a a1)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a2))
                    | tree.RebaseAction.NotEqualReplace new_right =>
                      let rl ←
                        lock_api.rwlock.RwLock.new
                          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
                          orig_hash
                      let a ←
                        triomphe.arc.Arc.Insts.CoreCloneClone.clone new_left
                      let a1 ←
                        triomphe.arc.Arc.new (tree.Tree.Node rl a new_right)
                      ok (core.result.Result.Ok
                        (tree.RebaseAction.NotEqualReplace a1))
                    | tree.RebaseAction.EqualNoop =>
                      ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace
                        base))
                    | tree.RebaseAction.EqualReplace _ =>
                      ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace
                        base))
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                    error.Error) residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  (tree.RebaseAction (tree.Tree T)) (core.convert.FromSame
                  error.Error) residual
        else ok (core.result.Result.Err error.Error.InvalidRebaseNode)
      | tree.Tree.Zero _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
    | tree.Tree.Zero z1 =>
      match t1 with
      | tree.Tree.Leaf _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
      | tree.Tree.PackedLeaf _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
      | tree.Tree.Node _ _ _ =>
        ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
      | tree.Tree.Zero z2 =>
        let b1 ← lift (core.cmp.impls.PartialEqUsize.eq z1 z2)
        if b1
        then ok (core.result.Result.Ok (tree.RebaseAction.EqualReplace base))
        else ok (core.result.Result.Ok tree.RebaseAction.NotEqualNoop)
partial_fixpoint

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::intra_rebase]:
    Source: 'src/tree.rs', lines 433:4-491:5
    Visibility: public -/
def tree.Tree.intra_rebase
  {T : Type} (ValueInst : Value T) (orig : triomphe.arc.Arc (tree.Tree T))
  (known_subtrees : std.collections.hash.map.HashMap (Std.Usize ×
  (alloy_primitives.bits.fixed.FixedBytes 32#usize)) (triomphe.arc.Arc
  (tree.Tree T)) std.hash.random.RandomState Global)
  (current_depth : Std.Usize) :
  Result ((core.result.Result (tree.IntraRebaseAction (tree.Tree T))
    error.Error) × (std.collections.hash.map.HashMap (Std.Usize ×
    (alloy_primitives.bits.fixed.FixedBytes 32#usize)) (triomphe.arc.Arc
    (tree.Tree T)) std.hash.random.RandomState Global))
  := do
  let t ← triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref orig
  match t with
  | tree.Tree.Leaf _ =>
    ok (core.result.Result.Ok tree.IntraRebaseAction.Noop, known_subtrees)
  | tree.Tree.PackedLeaf _ =>
    ok (core.result.Result.Ok tree.IntraRebaseAction.Noop, known_subtrees)
  | tree.Tree.Node hash left right =>
    if current_depth > 0#usize
    then
      let rlrg ←
        lock_api.rwlock.RwLock.read
          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
          hash
      let hash1 ←
        lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
          parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend
          rlrg
      let b ← alloy_primitives.bits.fixed.FixedBytes.is_zero hash1
      if b
      then
        ok (core.result.Result.Err error.Error.IntraRebaseZeroHash,
          known_subtrees)
      else
        let o ←
          std.collections.hash.map.HashMap.get (Pair.Insts.CoreCmpEq
            core.cmp.EqUsize
            (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq 32#usize))
            (Pair.Insts.CoreHashHash Usize.Insts.CoreHashHash
            (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash
            32#usize))
            std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
            (core.borrow.Borrow.Blanket (Std.Usize ×
            (alloy_primitives.bits.fixed.FixedBytes 32#usize)))
            (Pair.Insts.CoreHashHash Usize.Insts.CoreHashHash
            (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash
            32#usize)) (Pair.Insts.CoreCmpEq core.cmp.EqUsize
            (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq 32#usize))
            known_subtrees (current_depth, hash1)
        match o with
        | none =>
          let i ← current_depth - 1#usize
          let (r, known_subtrees1) ←
            tree.Tree.intra_rebase ValueInst left known_subtrees i
          let cf ← core.result.Result.Insts.CoreOpsTry.branch r
          match cf with
          | core.ops.control_flow.ControlFlow.Continue val =>
            let (r1, known_subtrees2) ←
              tree.Tree.intra_rebase ValueInst right known_subtrees1 i
            let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
            match cf1 with
            | core.ops.control_flow.ControlFlow.Continue val1 =>
              match val with
              | tree.IntraRebaseAction.Noop =>
                let action ←
                  match val1 with
                  | tree.IntraRebaseAction.Noop =>
                    ok tree.IntraRebaseAction.Noop
                  | tree.IntraRebaseAction.Replace new_right =>
                    do
                    let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone left
                    let a1 ← tree.Tree.node ValueInst a new_right hash1
                    ok (tree.IntraRebaseAction.Replace a1)
                let new_subtree ←
                  match action with
                  | tree.IntraRebaseAction.Noop =>
                    triomphe.arc.Arc.Insts.CoreCloneClone.clone orig
                  | tree.IntraRebaseAction.Replace new =>
                    triomphe.arc.Arc.Insts.CoreCloneClone.clone new
                let (existing_entry, known_subtrees3) ←
                  std.collections.hash.map.HashMap.insert (Pair.Insts.CoreCmpEq
                    core.cmp.EqUsize
                    (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq
                    32#usize)) (Pair.Insts.CoreHashHash
                    Usize.Insts.CoreHashHash
                    (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash
                    32#usize))
                    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
                    known_subtrees2 (current_depth, hash1) new_subtree
                let b1 := core.option.Option.is_some existing_entry
                if b1
                then
                  ok (core.result.Result.Err
                    error.Error.IntraRebaseRepeatVisit, known_subtrees3)
                else ok (core.result.Result.Ok action, known_subtrees3)
              | tree.IntraRebaseAction.Replace new_left =>
                match val1 with
                | tree.IntraRebaseAction.Noop =>
                  let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone right
                  let new ← tree.Tree.node ValueInst new_left a hash1
                  let new_subtree ←
                    triomphe.arc.Arc.Insts.CoreCloneClone.clone new
                  let (existing_entry, known_subtrees3) ←
                    std.collections.hash.map.HashMap.insert
                      (Pair.Insts.CoreCmpEq core.cmp.EqUsize
                      (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq
                      32#usize)) (Pair.Insts.CoreHashHash
                      Usize.Insts.CoreHashHash
                      (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash
                      32#usize))
                      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
                      known_subtrees2 (current_depth, hash1) new_subtree
                  let b1 := core.option.Option.is_some existing_entry
                  if b1
                  then
                    ok (core.result.Result.Err
                      error.Error.IntraRebaseRepeatVisit, known_subtrees3)
                  else
                    ok (core.result.Result.Ok (tree.IntraRebaseAction.Replace
                      new), known_subtrees3)
                | tree.IntraRebaseAction.Replace new_right =>
                  let new ← tree.Tree.node ValueInst new_left new_right hash1
                  let new_subtree ←
                    triomphe.arc.Arc.Insts.CoreCloneClone.clone new
                  let (existing_entry, known_subtrees3) ←
                    std.collections.hash.map.HashMap.insert
                      (Pair.Insts.CoreCmpEq core.cmp.EqUsize
                      (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq
                      32#usize)) (Pair.Insts.CoreHashHash
                      Usize.Insts.CoreHashHash
                      (alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash
                      32#usize))
                      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
                      known_subtrees2 (current_depth, hash1) new_subtree
                  let b1 := core.option.Option.is_some existing_entry
                  if b1
                  then
                    ok (core.result.Result.Err
                      error.Error.IntraRebaseRepeatVisit, known_subtrees3)
                  else
                    ok (core.result.Result.Ok (tree.IntraRebaseAction.Replace
                      new), known_subtrees3)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r2 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  (tree.IntraRebaseAction (tree.Tree T)) (core.convert.FromSame
                  error.Error) residual
              ok (r2, known_subtrees2)
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r1 ←
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                (tree.IntraRebaseAction (tree.Tree T)) (core.convert.FromSame
                error.Error) residual
            ok (r1, known_subtrees1)
        | some known_subtree =>
          let a ← triomphe.arc.Arc.Insts.CoreCloneClone.clone known_subtree
          ok (core.result.Result.Ok (tree.IntraRebaseAction.Replace a),
            known_subtrees)
    else
      ok (core.result.Result.Err error.Error.IntraRebaseZeroDepth,
        known_subtrees)
  | tree.Tree.Zero _ =>
    ok (core.result.Result.Ok tree.IntraRebaseAction.Noop, known_subtrees)
partial_fixpoint

end milhouse
