-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Tree.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open milhouse

/-- [core::borrow::{impl core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::hash::impls::{impl core::hash::Hash for usize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<usize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<usize>}::hash"]
axiom Usize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Usize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for (T, B)}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 893:20-893:60
    Name pattern: [core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash"]
axiom Pair.Insts.CoreHashHash.hash
  {T : Type} {B : Type} {S : Type} (HashInst : core.hash.Hash T) (HashInst1 :
  core.hash.Hash B) (HasherInst : core.hash.Hasher S) :
  (T × B) → S → Result S

/-- [core::hint::must_use]:
    Source: '/rustc/library/core/src/hint.rs', lines 613:0-613:39
    Name pattern: [core::hint::must_use]
    Visibility: public -/
@[rust_fun "core::hint::must_use"]
axiom core.hint.must_use {T : Type} : T → Result T

/-- [core::iter::traits::iterator::Iterator::size_hint]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 189:4-189:49
    Name pattern: [core::iter::traits::iterator::Iterator::size_hint]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::size_hint"]
axiom core.iter.traits.iterator.Iterator.size_hint.default
  {Self : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) :
  Self → Result (Std.Usize × (Option Std.Usize))

/-- [core::marker::{impl core::clone::Clone for core::marker::PhantomData<T>}::clone]:
    Source: '/rustc/library/core/src/marker.rs', lines 848:4-848:27
    Name pattern: [core::marker::{core::clone::Clone<core::marker::PhantomData<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::marker::{core::clone::Clone<core::marker::PhantomData<@T>>}::clone"]
axiom core.marker.PhantomData.Insts.CoreCloneClone.clone
  {T : Type} : core.marker.PhantomData T → Result (core.marker.PhantomData T)

/-- [core::mem::size_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 375:0-375:34
    Name pattern: [core::mem::size_of]
    Visibility: public -/
@[rust_fun "core::mem::size_of"]
axiom core.mem.size_of (T : Type) : Result Std.Usize

/-- [core::mem::take]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 894:0-894:56
    Name pattern: [core::mem::take]
    Visibility: public -/
@[rust_fun "core::mem::take"]
axiom core.mem.take
  {T : Type} (defaultDefaultInst : core.default.Default T) :
  T → Result (T × T)

/-- [core::num::{usize}::trailing_zeros]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 177:8-177:48
    Name pattern: [core::num::{usize}::trailing_zeros]
    Visibility: public -/
@[rust_fun "core::num::{usize}::trailing_zeros"]
axiom core.num.Usize.trailing_zeros : Std.Usize → Result Std.U32

/-- [core::num::{u128}::checked_pow]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2399:8-2399:68
    Name pattern: [core::num::{u128}::checked_pow]
    Visibility: public -/
@[rust_fun "core::num::{u128}::checked_pow"]
axiom core.num.U128.checked_pow
  : Std.U128 → Std.U32 → Result (Option Std.U128)

/-- [core::num::{u128}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2584:8-2584:60
    Name pattern: [core::num::{u128}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u128}::saturating_mul"]
axiom core.num.U128.saturating_mul : Std.U128 → Std.U128 → Result Std.U128

/-- [core::num::{usize}::pow]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3634:8-3634:48
    Name pattern: [core::num::{usize}::pow]
    Visibility: public -/
@[rust_fun "core::num::{usize}::pow"]
axiom core.num.Usize.pow : Std.Usize → Std.U32 → Result Std.Usize

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3787:8-3787:54
    Name pattern: [core::num::{usize}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{usize}::div_ceil"]
axiom core.num.Usize.div_ceil : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::num::{usize}::checked_next_power_of_two]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3956:8-3956:68
    Name pattern: [core::num::{usize}::checked_next_power_of_two]
    Visibility: public -/
@[rust_fun "core::num::{usize}::checked_next_power_of_two"]
axiom core.num.Usize.checked_next_power_of_two
  : Std.Usize → Result (Option Std.Usize)

/-- [core::option::{core::option::Option<T>}::is_some_and]:
    Source: '/rustc/library/core/src/option.rs', lines 659:4-659:96
    Name pattern: [core::option::{core::option::Option<@T>}::is_some_and]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_some_and"]
axiom core.option.Option.is_some_and
  {T : Type} {T1 : Type} (opsfunctionFnOnceT1TupleTBoolInst :
  core.ops.function.FnOnce T1 T Bool) :
  Option T → T1 → Result Bool

/-- [core::option::{core::option::Option<T>}::is_none_or]:
    Source: '/rustc/library/core/src/option.rs', lines 708:4-708:95
    Name pattern: [core::option::{core::option::Option<@T>}::is_none_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_none_or"]
axiom core.option.Option.is_none_or
  {T : Type} {T1 : Type} (opsfunctionFnOnceT1TupleTBoolInst :
  core.ops.function.FnOnce T1 T Bool) :
  Option T → T1 → Result Bool

/-- [core::option::{core::option::Option<T>}::as_ref]:
    Source: '/rustc/library/core/src/option.rs', lines 742:4-742:44
    Name pattern: [core::option::{core::option::Option<@T>}::as_ref]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::as_ref"]
axiom core.option.Option.as_ref {T : Type} : Option T → Result (Option T)

/-- [core::option::{core::option::Option<T>}::unwrap_or_default]:
    Source: '/rustc/library/core/src/option.rs', lines 1091:4-1093:27
    Name pattern: [core::option::{core::option::Option<@T>}::unwrap_or_default]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::unwrap_or_default"]
axiom core.option.Option.unwrap_or_default
  {T : Type} (defaultDefaultInst : core.default.Default T) :
  Option T → Result T

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1158:4-1160:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<T>}::map_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1222:4-1225:28
    Name pattern: [core::option::{core::option::Option<@T>}::map_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map_or"]
axiom core.option.Option.map_or
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → U → F → Result U

/-- [core::option::{core::option::Option<T>}::or]:
    Source: '/rustc/library/core/src/option.rs', lines 1617:4-1619:28
    Name pattern: [core::option::{core::option::Option<@T>}::or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::or"]
axiom core.option.Option.or
  {T : Type} : Option T → Option T → Result (Option T)

/-- [core::option::{core::option::Option<(T, U)>}::unzip]:
    Source: '/rustc/library/core/src/option.rs', lines 2107:4-2107:48
    Name pattern: [core::option::{core::option::Option<(@T, @U)>}::unzip]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<(@T, @U)>}::unzip"]
axiom core.option.OptionPair.unzip
  {T : Type} {U : Type} : Option (T × U) → Result ((Option T) × (Option U))

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    Source: '/rustc/library/core/src/option.rs', lines 2131:4-2133:16
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::copied]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
axiom core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T)

/-- [core::option::{core::option::Option<&'_0 T>}::cloned]:
    Source: '/rustc/library/core/src/option.rs', lines 2157:4-2159:17
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::cloned]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::cloned"]
axiom core.option.OptionShared0T.cloned
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2868:4-2868:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2882:4-2882:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::ne]:
    Source: '/rustc/library/core/src/tuple.rs', lines 34:16-34:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne"]
axiom Pair.Insts.CoreCmpPartialEqPair.ne
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}::partial_cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 69:16-69:76
    Name pattern: [core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp"]
axiom Pair.Insts.CoreCmpPartialOrdPair.partial_cmp
  {U : Type} {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd U U)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  (U × T) → (U × T) → Result (Option Ordering)

/-- [core::tuple::{impl core::cmp::Ord for (U, T)}::cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 114:16-114:60
    Name pattern: [core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp"]
axiom Pair.Insts.CoreCmpOrd.cmp
  {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U) (cmpOrdInst1 :
  core.cmp.Ord T) :
  (U × T) → (U × T) → Result Ordering

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1034:4-1037:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get"]
axiom std.collections.hash.map.HashMap.get
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option V)

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1332:4-1332:53
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert"]
axiom std.collections.hash.map.HashMap.insert
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.map.HashMap K V S A → K → V → Result ((Option V)
    × (std.collections.hash.map.HashMap K V S A))

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::finish]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 140:4-140:27
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  : std.hash.random.DefaultHasher → Result Std.U64

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::write]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 130:4-130:35
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
  :
  std.hash.random.DefaultHasher → Slice Std.U8 → Result
    std.hash.random.DefaultHasher

/-- [std::hash::random::{impl core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}::build_hasher]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 83:4-83:43
    Name pattern: [std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher"]
axiom
  std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
  : std.hash.random.RandomState → Result std.hash.random.DefaultHasher

/-- [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::VacantEntry<'a, K, V, A>}::insert]:
    Source: '/rustc/library/alloc/src/collections/btree/map/entry.rs', lines 425:4-425:46
    Name pattern: [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::VacantEntry<'a, @K, @V, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::VacantEntry<'a, @K, @V, @A>}::insert"]
axiom alloc.collections.btree.map.entry.VacantEntry.insert
  {K : Type} {V : Type} {A : Type} (corecmpOrdInst : core.cmp.Ord K)
  (corecloneCloneInst : core.clone.Clone A) :
  alloc.collections.btree.map.entry.VacantEntry K V A → V → Result (V × (V
    → alloc.collections.btree.map.entry.VacantEntry K V A))

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, A>}::get]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 717:4-720:15
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get"]
axiom alloc.collections.btree.map.BTreeMap.get
  {K : Type} {V : Type} {A : Type} {Q : Type} (corecloneCloneInst :
  core.clone.Clone A) (coreborrowBorrowInst : core.borrow.Borrow K Q)
  (corecmpOrdInst : core.cmp.Ord K) (corecmpOrdInst1 : core.cmp.Ord Q) :
  alloc.collections.btree.map.BTreeMap K V A → Q → Result (Option V)

/-- [alloc::fmt::format]:
    Source: '/rustc/library/alloc/src/fmt.rs', lines 649:0-649:52
    Name pattern: [alloc::fmt::format]
    Visibility: public -/
@[rust_fun "alloc::fmt::format"]
axiom alloc.fmt.format : core.fmt.Arguments → Result String

/-- [alloc::vec::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::into_iter::IntoIter<T, A>}::size_hint]:
    Source: '/rustc/library/alloc/src/vec/into_iter.rs', lines 273:4-273:49
    Name pattern: [alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::size_hint]
    Visibility: public -/
@[rust_fun
  "alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::size_hint"]
axiom
  alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.size_hint
  {T : Type} {A : Type} :
  alloc.vec.into_iter.IntoIter T → Result (Std.Usize × (Option Std.Usize))

/-- [alloc::vec::into_iter::{impl core::iter::traits::double_ended::DoubleEndedIterator<T> for alloc::vec::into_iter::IntoIter<T, A>}::next_back]:
    Source: '/rustc/library/alloc/src/vec/into_iter.rs', lines 426:4-426:40
    Name pattern: [alloc::vec::into_iter::{core::iter::traits::double_ended::DoubleEndedIterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::next_back]
    Visibility: public -/
@[rust_fun
  "alloc::vec::into_iter::{core::iter::traits::double_ended::DoubleEndedIterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::next_back"]
axiom
  alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsDouble_endedDoubleEndedIterator.next_back
  {T : Type} {A : Type} :
  alloc.vec.into_iter.IntoIter T → Result ((Option T) ×
    (alloc.vec.into_iter.IntoIter T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::reserve]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1460:4-1460:48
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::reserve]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::reserve"]
axiom alloc.vec.Vec.reserve
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2872:4-2872:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3125:4-3125:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [alloy_primitives::bits::fixed::{impl core::clone::Clone for alloy_primitives::bits::fixed::FixedBytes<N>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 16:4-16:9
    Name pattern: [alloy_primitives::bits::fixed::{core::clone::Clone<alloy_primitives::bits::fixed::FixedBytes<@N>>}::clone]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::clone::Clone<alloy_primitives::bits::fixed::FixedBytes<@N>>}::clone"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCloneClone.clone
  {N : Std.Usize} :
  alloy_primitives.bits.fixed.FixedBytes N → Result
    (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{impl core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<N>> for alloy_primitives::bits::fixed::FixedBytes<N>}::eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 18:4-18:13
    Name pattern: [alloy_primitives::bits::fixed::{core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>}::eq]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::cmp::PartialEq<alloy_primitives::bits::fixed::FixedBytes<@N>, alloy_primitives::bits::fixed::FixedBytes<@N>>}::eq"]
axiom
  alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpPartialEqFixedBytes.eq
  {N : Std.Usize} :
  alloy_primitives.bits.fixed.FixedBytes N →
    alloy_primitives.bits.fixed.FixedBytes N → Result Bool

/-- [alloy_primitives::bits::fixed::{impl core::cmp::Eq for alloy_primitives::bits::fixed::FixedBytes<N>}::assert_fields_are_eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 19:4-19:6
    Name pattern: [alloy_primitives::bits::fixed::{core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>}::assert_fields_are_eq]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::cmp::Eq<alloy_primitives::bits::fixed::FixedBytes<@N>>}::assert_fields_are_eq"]
axiom
  alloy_primitives.bits.fixed.FixedBytes.Insts.CoreCmpEq.assert_fields_are_eq
  {N : Std.Usize} : alloy_primitives.bits.fixed.FixedBytes N → Result Unit

/-- [alloy_primitives::bits::fixed::{impl core::hash::Hash for alloy_primitives::bits::fixed::FixedBytes<N>}::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 22:4-22:8
    Name pattern: [alloy_primitives::bits::fixed::{core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>}::hash]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::hash::Hash<alloy_primitives::bits::fixed::FixedBytes<@N>>}::hash"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreHashHash.hash
  {__H : Type} {N : Std.Usize} (corehashHasherInst : core.hash.Hasher __H) :
  alloy_primitives.bits.fixed.FixedBytes N → __H → Result __H

/-- [alloy_primitives::bits::fixed::{impl core::default::Default for alloy_primitives::bits::fixed::FixedBytes<N>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 41:4-41:24
    Name pattern: [alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{core::default::Default<alloy_primitives::bits::fixed::FixedBytes<@N>>}::default"]
axiom alloy_primitives.bits.fixed.FixedBytes.Insts.CoreDefaultDefault.default
  (N : Std.Usize) : Result (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 337:4-337:24
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO]
    Visibility: public -/
@[rust_const
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::ZERO"]
axiom alloy_primitives.bits.fixed.FixedBytes.ZERO (N : Std.Usize)
  : Result (alloy_primitives.bits.fixed.FixedBytes N)

/-- [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<N>}::is_zero]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 581:4-581:33
    Name pattern: [alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::is_zero]
    Visibility: public -/
@[rust_fun
  "alloy_primitives::bits::fixed::{alloy_primitives::bits::fixed::FixedBytes<@N>}::is_zero"]
axiom alloy_primitives.bits.fixed.FixedBytes.is_zero
  {N : Std.Usize} : alloy_primitives.bits.fixed.FixedBytes N → Result Bool

/-- [arbitrary::foreign::alloc::vec::{impl arbitrary::Arbitrary<'a> for alloc::vec::Vec<A>}::arbitrary]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.1/src/foreign/alloc/vec.rs', lines 10:4-10:58
    Name pattern: [arbitrary::foreign::alloc::vec::{arbitrary::Arbitrary<'a, alloc::vec::Vec<@A>>}::arbitrary]
    Visibility: public -/
@[rust_fun
  "arbitrary::foreign::alloc::vec::{arbitrary::Arbitrary<'a, alloc::vec::Vec<@A>>}::arbitrary"]
axiom alloc.vec.Vec.Insts.ArbitraryArbitrary.arbitrary
  {A : Type} (ArbitraryInst : arbitrary.Arbitrary A) :
  arbitrary.unstructured.Unstructured → Result ((core.result.Result
    (alloc.vec.Vec A) arbitrary.error.Error) ×
    arbitrary.unstructured.Unstructured)

/-- [arbitrary::Arbitrary::arbitrary_take_rest]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.1/src/lib.rs', lines 216:4-216:67
    Name pattern: [arbitrary::Arbitrary::arbitrary_take_rest]
    Visibility: public -/
@[trait_default, rust_fun "arbitrary::Arbitrary::arbitrary_take_rest"]
axiom arbitrary.Arbitrary.arbitrary_take_rest.default
  {Self : Type} (ArbitraryInst : arbitrary.Arbitrary Self) :
  arbitrary.unstructured.Unstructured → Result (core.result.Result Self
    arbitrary.error.Error)

/-- [arbitrary::Arbitrary::size_hint]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.1/src/lib.rs', lines 320:4-320:56
    Name pattern: [arbitrary::Arbitrary::size_hint]
    Visibility: public -/
@[trait_default, rust_fun "arbitrary::Arbitrary::size_hint"]
axiom arbitrary.Arbitrary.size_hint.default
  {Self : Type} (ArbitraryInst : arbitrary.Arbitrary Self) :
  Std.Usize → Result (Std.Usize × (Option Std.Usize))

/-- [arbitrary::Arbitrary::try_size_hint]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.1/src/lib.rs', lines 423:4-423:89
    Name pattern: [arbitrary::Arbitrary::try_size_hint]
    Visibility: public -/
@[trait_default, rust_fun "arbitrary::Arbitrary::try_size_hint"]
axiom arbitrary.Arbitrary.try_size_hint.default
  {Self : Type} (ArbitraryInst : arbitrary.Arbitrary Self) :
  Std.Usize → Result (core.result.Result (Std.Usize × (Option Std.Usize))
    arbitrary.MaxRecursionReached)

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 371:4-371:44
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::new]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::new"]
axiom lock_api.rwlock.RwLock.new
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  T → Result (lock_api.rwlock.RwLock R T)

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::read]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 467:4-467:51
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::read]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::read"]
axiom lock_api.rwlock.RwLock.read
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLock R T → Result (lock_api.rwlock.RwLockReadGuard R T
    Clause0_GuardMarker)

/-- [lock_api::rwlock::{lock_api::rwlock::RwLock<R, T>}::get_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 527:4-527:39
    Name pattern: [lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::get_mut]
    Visibility: public -/
@[rust_fun "lock_api::rwlock::{lock_api::rwlock::RwLock<@R, @T>}::get_mut"]
axiom lock_api.rwlock.RwLock.get_mut
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLock R T → Result (T × (T → lock_api.rwlock.RwLock R
    T))

/-- [lock_api::rwlock::{impl core::ops::deref::Deref<T> for lock_api::rwlock::RwLockReadGuard<'a, R, T, Clause0_GuardMarker>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 1365:4-1365:25
    Name pattern: [lock_api::rwlock::{core::ops::deref::Deref<lock_api::rwlock::RwLockReadGuard<'a, @R, @T, @Clause0_GuardMarker>, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "lock_api::rwlock::{core::ops::deref::Deref<lock_api::rwlock::RwLockReadGuard<'a, @R, @T, @Clause0_GuardMarker>, @T>}::deref"]
axiom lock_api.rwlock.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
  {R : Type} {T : Type} {Clause0_GuardMarker : Type} (RawRwLockInst :
  lock_api.rwlock.RawRwLock R Clause0_GuardMarker) :
  lock_api.rwlock.RwLockReadGuard R T Clause0_GuardMarker → Result T

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::unlock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 129:4-129:34
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::try_lock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 116:4-116:37
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Bool

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::lock_shared]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 107:4-107:25
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_shared]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_shared"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_shared
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::unlock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 94:4-94:37
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::unlock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.unlock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::try_lock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 80:4-80:40
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::try_lock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.try_lock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Bool

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::lock_exclusive]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 67:4-67:28
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_exclusive]
    Visibility: public -/
@[rust_fun
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::lock_exclusive"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.lock_exclusive
  : parking_lot.raw_rwlock.RawRwLock → Result Unit

/-- [parking_lot::raw_rwlock::{impl lock_api::rwlock::RawRwLock<lock_api::GuardNoSend> for parking_lot::raw_rwlock::RawRwLock}::INIT]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 60:4-60:25
    Name pattern: [parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::INIT]
    Visibility: public -/
@[rust_const
  "parking_lot::raw_rwlock::{lock_api::rwlock::RawRwLock<parking_lot::raw_rwlock::RawRwLock, lock_api::GuardNoSend>}::INIT"]
axiom
  parking_lot.raw_rwlock.RawRwLock.Insts.Lock_apiRwlockRawRwLockGuardNoSend.INIT
  : Result parking_lot.raw_rwlock.RawRwLock

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 779:4-779:31
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::new]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::new"]
axiom smallvec.SmallVec.new
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  Result (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::from_vec]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 825:4-825:57
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::from_vec]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::from_vec"]
axiom smallvec.SmallVec.from_vec
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  alloc.vec.Vec Clause0_Item → Result (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::inline_size]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 946:4-946:38
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::inline_size]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::inline_size"]
axiom smallvec.SmallVec.inline_size
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result Std.Usize

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::is_empty]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 958:4-958:34
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::is_empty]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::is_empty"]
axiom smallvec.SmallVec.is_empty
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result Bool

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::push]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 1114:4-1114:42
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::push]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::push"]
axiom smallvec.SmallVec.push
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Clause0_Item → Result
    (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::pop]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 1130:4-1130:44
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::pop]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::pop"]
axiom smallvec.SmallVec.pop
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result ((Option Clause0_Item) ×
    (smallvec.SmallVec A Clause0_Item))

/-- [smallvec::{impl smallvec::Array<T> for [T; N]}::size]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 2409:4-2409:22
    Name pattern: [smallvec::{smallvec::Array<[@T; @N], @T>}::size]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::Array<[@T; @N], @T>}::size"]
axiom Array.Insts.SmallvecArray.size
  (T : Type) (N : Std.Usize) : Result Std.Usize

/-- [ssz::decode::Decode::ssz_fixed_len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/decode.rs', lines 111:4-111:31
    Name pattern: [ssz::decode::Decode::ssz_fixed_len]
    Visibility: public -/
@[trait_default, rust_fun "ssz::decode::Decode::ssz_fixed_len"]
axiom ssz.decode.Decode.ssz_fixed_len.default
  {Self : Type} (DecodeInst : ssz.decode.Decode Self) : Result Std.Usize

/-- [ssz::decode::read_offset]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/decode.rs', lines 353:0-353:62
    Name pattern: [ssz::decode::read_offset]
    Visibility: public -/
@[rust_fun "ssz::decode::read_offset"]
axiom ssz.decode.read_offset
  :
  Slice Std.U8 → Result (core.result.Result Std.Usize ssz.decode.DecodeError)

/-- [ssz::encode::Encode::ssz_fixed_len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 26:4-26:31
    Name pattern: [ssz::encode::Encode::ssz_fixed_len]
    Visibility: public -/
@[trait_default, rust_fun "ssz::encode::Encode::ssz_fixed_len"]
axiom ssz.encode.Encode.ssz_fixed_len.default
  {Self : Type} (EncodeInst : ssz.encode.Encode Self) : Result Std.Usize

/-- [ssz::encode::Encode::as_ssz_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 39:4-39:37
    Name pattern: [ssz::encode::Encode::as_ssz_bytes]
    Visibility: public -/
@[trait_default, rust_fun "ssz::encode::Encode::as_ssz_bytes"]
axiom ssz.encode.Encode.as_ssz_bytes.default
  {Self : Type} (EncodeInst : ssz.encode.Encode Self) :
  Self → Result (alloc.vec.Vec Std.U8)

/-- [ssz::encode::{ssz::encode::SszEncoder<'a>}::container]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 95:4-95:74
    Name pattern: [ssz::encode::{ssz::encode::SszEncoder<'a>}::container]
    Visibility: public -/
@[rust_fun "ssz::encode::{ssz::encode::SszEncoder<'a>}::container"]
axiom ssz.encode.SszEncoder.container
  :
  alloc.vec.Vec Std.U8 → Std.Usize → Result (ssz.encode.SszEncoder ×
    (ssz.encode.SszEncoder → alloc.vec.Vec Std.U8))

/-- [ssz::encode::{ssz::encode::SszEncoder<'a>}::append]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 106:4-106:49
    Name pattern: [ssz::encode::{ssz::encode::SszEncoder<'a>}::append]
    Visibility: public -/
@[rust_fun "ssz::encode::{ssz::encode::SszEncoder<'a>}::append"]
axiom ssz.encode.SszEncoder.append
  {T : Type} (EncodeInst : ssz.encode.Encode T) :
  ssz.encode.SszEncoder → T → Result (ssz.encode.SszEncoder ×
    (ssz.encode.SszEncoder → ssz.encode.SszEncoder))

/-- [ssz::encode::{ssz::encode::SszEncoder<'a>}::finalize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 129:4-129:46
    Name pattern: [ssz::encode::{ssz::encode::SszEncoder<'a>}::finalize]
    Visibility: public -/
@[rust_fun "ssz::encode::{ssz::encode::SszEncoder<'a>}::finalize"]
axiom ssz.encode.SszEncoder.finalize
  :
  ssz.encode.SszEncoder → Result ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec
    Std.U8 → ssz.encode.SszEncoder) × (ssz.encode.SszEncoder →
    ssz.encode.SszEncoder))

/-- [ssz::BYTES_PER_LENGTH_OFFSET]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/lib.rs', lines 57:0-57:40
    Name pattern: [ssz::BYTES_PER_LENGTH_OFFSET]
    Visibility: public -/
@[rust_const "ssz::BYTES_PER_LENGTH_OFFSET"]
axiom ssz.BYTES_PER_LENGTH_OFFSET : Result Std.Usize

/-- [triomphe::arc::{triomphe::arc::Arc<T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 80:4-80:31
    Name pattern: [triomphe::arc::{triomphe::arc::Arc<@T>}::new]
    Visibility: public -/
@[rust_fun "triomphe::arc::{triomphe::arc::Arc<@T>}::new"]
axiom triomphe.arc.Arc.new {T : Type} : T → Result (triomphe.arc.Arc T)

/-- [triomphe::arc::{triomphe::arc::Arc<T>}::ptr_eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 281:4-281:52
    Name pattern: [triomphe::arc::{triomphe::arc::Arc<@T>}::ptr_eq]
    Visibility: public -/
@[rust_fun "triomphe::arc::{triomphe::arc::Arc<@T>}::ptr_eq"]
axiom triomphe.arc.Arc.ptr_eq
  {T : Type} : triomphe.arc.Arc T → triomphe.arc.Arc T → Result Bool

/-- [triomphe::arc::{impl core::clone::Clone for triomphe::arc::Arc<T>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 450:4-450:27
    Name pattern: [triomphe::arc::{core::clone::Clone<triomphe::arc::Arc<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::clone::Clone<triomphe::arc::Arc<@T>>}::clone"]
axiom triomphe.arc.Arc.Insts.CoreCloneClone.clone
  {T : Type} : triomphe.arc.Arc T → Result (triomphe.arc.Arc T)

/-- [triomphe::arc::{impl core::ops::deref::Deref<T> for triomphe::arc::Arc<T>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 490:4-490:25
    Name pattern: [triomphe::arc::{core::ops::deref::Deref<triomphe::arc::Arc<@T>, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::ops::deref::Deref<triomphe::arc::Arc<@T>, @T>}::deref"]
axiom triomphe.arc.Arc.Insts.CoreOpsDerefDeref.deref
  {T : Type} : triomphe.arc.Arc T → Result T

/-- [triomphe::arc::{impl core::cmp::PartialEq<triomphe::arc::Arc<T>> for triomphe::arc::Arc<T>}::ne]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 673:4-673:40
    Name pattern: [triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::ne]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::ne"]
axiom triomphe.arc.Arc.Insts.CoreCmpPartialEqArc.ne
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  triomphe.arc.Arc T → triomphe.arc.Arc T → Result Bool

/-- [triomphe::arc::{impl core::cmp::PartialEq<triomphe::arc::Arc<T>> for triomphe::arc::Arc<T>}::eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 667:4-667:40
    Name pattern: [triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::cmp::PartialEq<triomphe::arc::Arc<@T>, triomphe::arc::Arc<@T>>}::eq"]
axiom triomphe.arc.Arc.Insts.CoreCmpPartialEqArc.eq
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  triomphe.arc.Arc T → triomphe.arc.Arc T → Result Bool

/-- [triomphe::arc::{impl core::convert::AsRef<T> for triomphe::arc::Arc<T>}::as_ref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 761:4-761:26
    Name pattern: [triomphe::arc::{core::convert::AsRef<triomphe::arc::Arc<@T>, @T>}::as_ref]
    Visibility: public -/
@[rust_fun
  "triomphe::arc::{core::convert::AsRef<triomphe::arc::Arc<@T>, @T>}::as_ref"]
axiom triomphe.arc.Arc.Insts.CoreConvertAsRef.as_ref
  {T : Type} : triomphe.arc.Arc T → Result T

/-- [vec_map::{vec_map::VacantEntry<'a, V>}::insert]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vec_map-0.8.2/src/lib.rs', lines 661:4-661:46
    Name pattern: [vec_map::{vec_map::VacantEntry<'a, @V>}::insert]
    Visibility: public -/
@[rust_fun "vec_map::{vec_map::VacantEntry<'a, @V>}::insert"]
axiom vec_map.VacantEntry.insert
  {V : Type} :
  vec_map.VacantEntry V → V → Result (V × (V → vec_map.VacantEntry V))

/-- [milhouse::list::{milhouse::list::List<T, N, U>}::intra_rebase]:
    Source: 'src/list.rs', lines 407:4-424:5
    Visibility: public -/
axiom list.List.intra_rebase
  {T : Type} {N : Type} {U : Type} (ValueInst : Value T)
  (typenummarker_traitsUnsignedInst : typenum.marker_traits.Unsigned N)
  (update_mapUpdateMapInst : update_map.UpdateMap U T) :
  list.List T N U → Result ((core.result.Result Unit error.Error) ×
    (list.List T N U))

