-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [std::collections::hash::map::HashMap]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 246:0-251:1
    Name pattern: [std::collections::hash::map::HashMap]
    Visibility: public -/
@[rust_type "std::collections::hash::map::HashMap"]
axiom std.collections.hash.map.HashMap (K : Type) (V : Type) (S : Type) (A :
  Type) : Type

/-- [std::hash::random::RandomState]
    Source: '/rustc/library/std/src/hash/random.rs', lines 35:0-35:22
    Name pattern: [std::hash::random::RandomState]
    Visibility: public -/
@[rust_type "std::hash::random::RandomState"]
axiom std.hash.random.RandomState : Type

/-- [std::hash::random::DefaultHasher]
    Source: '/rustc/library/std/src/hash/random.rs', lines 94:0-94:24
    Name pattern: [std::hash::random::DefaultHasher]
    Visibility: public -/
@[rust_type "std::hash::random::DefaultHasher"]
axiom std.hash.random.DefaultHasher : Type

/-- [lock_api::GuardNoSend]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/lib.rs', lines 103:0-103:22
    Name pattern: [lock_api::GuardNoSend]
    Visibility: public -/
@[rust_type "lock_api::GuardNoSend"]
axiom lock_api.GuardNoSend : Type

/-- [lock_api::rwlock::RwLock]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 330:0-330:31
    Name pattern: [lock_api::rwlock::RwLock]
    Visibility: public -/
@[rust_type "lock_api::rwlock::RwLock"]
axiom lock_api.rwlock.RwLock (R : Type) (T : Type) : Type

/-- [lock_api::rwlock::RwLockReadGuard]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 1226:0-1226:55
    Name pattern: [lock_api::rwlock::RwLockReadGuard]
    Visibility: public -/
@[rust_type "lock_api::rwlock::RwLockReadGuard"]
axiom lock_api.rwlock.RwLockReadGuard (R : Type) (T : Type)
  (Clause0_GuardMarker : Type) : Type

/-- [parking_lot::raw_rwlock::RawRwLock]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.12.3/src/raw_rwlock.rs', lines 55:0-55:20
    Name pattern: [parking_lot::raw_rwlock::RawRwLock]
    Visibility: public -/
@[rust_type "parking_lot::raw_rwlock::RawRwLock"]
axiom parking_lot.raw_rwlock.RawRwLock : Type

/-- [smallvec::SmallVec]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 768:0-768:29
    Name pattern: [smallvec::SmallVec]
    Visibility: public -/
@[rust_type "smallvec::SmallVec"]
axiom smallvec.SmallVec (A : Type) (Clause0_Item : Type) : Type

/-- [ssz::decode::DecodeError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/decode.rs', lines 12:0-12:20
    Name pattern: [ssz::decode::DecodeError]
    Visibility: public -/
@[rust_type "ssz::decode::DecodeError"]
axiom ssz.decode.DecodeError : Type

/-- [triomphe::arc::Arc]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/triomphe-0.1.14/src/arc.rs', lines 69:0-69:25
    Name pattern: [triomphe::arc::Arc]
    Visibility: public -/
@[rust_type "triomphe::arc::Arc"]
axiom triomphe.arc.Arc (T : Type) : Type

