-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: type definitions
import Aeneas
import Tree.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace milhouse

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher]
    Visibility: public -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [alloy_primitives::bits::fixed::FixedBytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 35:0-35:37
    Name pattern: [alloy_primitives::bits::fixed::FixedBytes]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::fixed::FixedBytes"]
def alloy_primitives.bits.fixed.FixedBytes (N : Std.Usize) := Array Std.U8 N

/-- Trait declaration: [lock_api::rwlock::RawRwLock]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 38:0-38:26
    Name pattern: [lock_api::rwlock::RawRwLock]
    Visibility: public -/
@[rust_trait "lock_api::rwlock::RawRwLock" (consts := ["INIT"])]
structure lock_api.rwlock.RawRwLock (Self : Type) (Self_GuardMarker : Type)
  where
  INIT : Result Self
  lock_shared : Self → Result Unit
  try_lock_shared : Self → Result Bool
  unlock_shared : Self → Result Unit
  lock_exclusive : Self → Result Unit
  try_lock_exclusive : Self → Result Bool
  unlock_exclusive : Self → Result Unit

/-- Trait declaration: [ssz::decode::Decode]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/decode.rs', lines 100:0-100:23
    Name pattern: [ssz::decode::Decode]
    Visibility: public -/
@[rust_trait "ssz::decode::Decode"]
structure ssz.decode.Decode (Self : Type) where
  is_ssz_fixed_len : Result Bool
  from_ssz_bytes : Slice Std.U8 → Result (core.result.Result Self
    ssz.decode.DecodeError)

/-- Trait declaration: [ssz::encode::Encode]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 9:0-9:16
    Name pattern: [ssz::encode::Encode]
    Visibility: public -/
@[rust_trait "ssz::encode::Encode"]
structure ssz.encode.Encode (Self : Type) where
  is_ssz_fixed_len : Result Bool
  ssz_append : Self → alloc.vec.Vec Std.U8 → Result (alloc.vec.Vec Std.U8)
  ssz_bytes_len : Self → Result Std.Usize

/-- [tree_hash::TreeHashType]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree_hash-0.12.0/src/lib.rs', lines 102:0-102:21
    Name pattern: [tree_hash::TreeHashType]
    Visibility: public -/
@[discriminant isize, rust_type "tree_hash::TreeHashType"]
inductive tree_hash.TreeHashType where
| Basic : tree_hash.TreeHashType
| Vector : tree_hash.TreeHashType
| List : tree_hash.TreeHashType
| Container : tree_hash.TreeHashType

/-- Trait declaration: [tree_hash::TreeHash]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree_hash-0.12.0/src/lib.rs', lines 109:0-109:18
    Name pattern: [tree_hash::TreeHash]
    Visibility: public -/
@[rust_trait "tree_hash::TreeHash"]
structure tree_hash.TreeHash (Self : Type) where
  tree_hash_type : Result tree_hash.TreeHashType
  tree_hash_packed_encoding : Self → Result (smallvec.SmallVec (Array Std.U8
    32#usize) Std.U8)
  tree_hash_packing_factor : Result Std.Usize
  tree_hash_root : Self → Result (alloy_primitives.bits.fixed.FixedBytes
    32#usize)

/-- [milhouse::error::Error]
    Source: 'src/error.rs', lines 4:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| OutOfBoundsUpdate : Std.Usize → Std.Usize → error.Error
| OutOfBoundsIterFrom : Std.Usize → Std.Usize → error.Error
| ListFull : Std.Usize → error.Error
| PackedLeafFull : Std.Usize → error.Error
| LeafUpdateMissing : Std.Usize → error.Error
| PackedLeafOutOfBounds : Std.Usize → Std.Usize → error.Error
| NodeUpdatesMissing : Std.Usize → error.Error
| InvalidListUpdate : error.Error
| InvalidVectorUpdate : error.Error
| WrongVectorLength : Std.Usize → Std.Usize → error.Error
| PushNotSupported : error.Error
| UpdateLeafError : error.Error
| UpdateLeavesError : error.Error
| InvalidRebaseNode : error.Error
| InvalidRebaseLeaf : error.Error
| BuilderInvalidDepth : Std.Usize → error.Error
| BuilderExpectedLeaf : error.Error
| BuilderStackEmptyMerge : error.Error
| BuilderStackEmptyMergeLeft : error.Error
| BuilderStackEmptyMergeRight : error.Error
| BuilderStackEmptyFinish : error.Error
| BuilderStackEmptyFinishLeft : error.Error
| BuilderStackEmptyFinishRight : error.Error
| BuilderStackEmptyFinalize : error.Error
| BuilderStackLeftover : error.Error
| BuilderFull : error.Error
| BulkUpdateUnclean : error.Error
| CowMissingEntry : error.Error
| LevelIterPendingUpdates : error.Error
| IntraRebaseZeroHash : error.Error
| IntraRebaseZeroDepth : error.Error
| IntraRebaseRepeatVisit : error.Error

/-- [milhouse::leaf::Leaf]
    Source: 'src/leaf.rs', lines 9:0-15:1
    Visibility: public -/
structure leaf.Leaf (T : Type) where
  hash : lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize)
  value : triomphe.arc.Arc T

/-- Trait declaration: [milhouse::Value]
    Source: 'src/lib.rs', lines 54:0-54:66
    Visibility: public -/
structure Value (Self : Type) where
  sszencodeEncodeInst : ssz.encode.Encode Self
  sszdecodeDecodeInst : ssz.decode.Decode Self
  tree_hashTreeHashInst : tree_hash.TreeHash Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corecloneCloneInst : core.clone.Clone Self

/-- [milhouse::packed_leaf::PackedLeaf]
    Source: 'src/packed_leaf.rs', lines 10:0-15:1
    Visibility: public -/
structure packed_leaf.PackedLeaf (T : Type) where
  hash : lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize)
  values : alloc.vec.Vec T

/-- [milhouse::tree::Tree]
    Source: 'src/tree.rs', lines 14:0-27:1
    Visibility: public -/
@[discriminant isize]
inductive tree.Tree (T : Type) where
| Leaf : leaf.Leaf T → tree.Tree T
| PackedLeaf : packed_leaf.PackedLeaf T → tree.Tree T
| Node :
  lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize) →
  triomphe.arc.Arc (tree.Tree T) →
  triomphe.arc.Arc (tree.Tree T) →
  tree.Tree T
| Zero : Std.Usize → tree.Tree T

/-- [milhouse::tree::RebaseAction]
    Source: 'src/tree.rs', lines 253:0-262:1
    Visibility: public -/
@[discriminant isize]
inductive tree.RebaseAction (T : Type) where
| NotEqualNoop : tree.RebaseAction T
| NotEqualReplace : triomphe.arc.Arc T → tree.RebaseAction T
| EqualNoop : tree.RebaseAction T
| EqualReplace : triomphe.arc.Arc T → tree.RebaseAction T

/-- [milhouse::tree::IntraRebaseAction]
    Source: 'src/tree.rs', lines 264:0-267:1
    Visibility: public -/
@[discriminant isize]
inductive tree.IntraRebaseAction (T : Type) where
| Noop : tree.IntraRebaseAction T
| Replace : triomphe.arc.Arc T → tree.IntraRebaseAction T

/-- [milhouse::utils::Length]
    Source: 'src/utils.rs', lines 25:0-25:29
    Visibility: public -/
@[reducible]
def utils.Length := Std.Usize

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::closure#1]
    Source: 'src/tree.rs', lines 324:25-337:21 -/
@[reducible]
def tree.Tree.rebase_on.closure_1 (T : Type) := Std.Usize

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::closure]
    Source: 'src/tree.rs', lines 317:42-317:97 -/
@[reducible]
def tree.Tree.rebase_on.closure (T : Type) := Unit

end milhouse
