-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [milhouse]: type definitions
import Aeneas
import Tree.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace milhouse

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher]
    Visibility: public -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [alloy_primitives::bits::fixed::FixedBytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-primitives-1.0.0/src/bits/fixed.rs', lines 35:0-35:37
    Name pattern: [alloy_primitives::bits::fixed::FixedBytes]
    Visibility: public -/
@[reducible, rust_type "alloy_primitives::bits::fixed::FixedBytes"]
def alloy_primitives.bits.fixed.FixedBytes (N : Std.Usize) := Array Std.U8 N

/-- Trait declaration: [lock_api::rwlock::RawRwLock]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lock_api-0.4.12/src/rwlock.rs', lines 38:0-38:26
    Name pattern: [lock_api::rwlock::RawRwLock]
    Visibility: public -/
@[rust_trait "lock_api::rwlock::RawRwLock" (consts := ["INIT"])]
structure lock_api.rwlock.RawRwLock (Self : Type) (Self_GuardMarker : Type)
  where
  INIT : Result Self
  lock_shared : Self → Result Unit
  try_lock_shared : Self → Result Bool
  unlock_shared : Self → Result Unit
  lock_exclusive : Self → Result Unit
  try_lock_exclusive : Self → Result Bool
  unlock_exclusive : Self → Result Unit

/-- Trait declaration: [smallvec::Array]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.13.2/src/lib.rs', lines 2321:0-2321:22
    Name pattern: [smallvec::Array]
    Visibility: public -/
@[rust_trait "smallvec::Array"]
structure smallvec.Array (Self : Type) (Self_Item : Type) where
  size : Result Std.Usize

/-- Trait declaration: [ssz::decode::Decode]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/decode.rs', lines 100:0-100:23
    Name pattern: [ssz::decode::Decode]
    Visibility: public -/
@[rust_trait "ssz::decode::Decode"]
structure ssz.decode.Decode (Self : Type) where
  is_ssz_fixed_len : Result Bool
  from_ssz_bytes : Slice Std.U8 → Result (core.result.Result Self
    ssz.decode.DecodeError)

/-- Trait declaration: [ssz::encode::Encode]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethereum_ssz-0.10.0/src/encode.rs', lines 9:0-9:16
    Name pattern: [ssz::encode::Encode]
    Visibility: public -/
@[rust_trait "ssz::encode::Encode"]
structure ssz.encode.Encode (Self : Type) where
  is_ssz_fixed_len : Result Bool
  ssz_append : Self → alloc.vec.Vec Std.U8 → Result (alloc.vec.Vec Std.U8)
  ssz_bytes_len : Self → Result Std.Usize

/-- [tree_hash::TreeHashType]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree_hash-0.12.0/src/lib.rs', lines 102:0-102:21
    Name pattern: [tree_hash::TreeHashType]
    Visibility: public -/
@[discriminant isize, rust_type "tree_hash::TreeHashType"]
inductive tree_hash.TreeHashType where
| Basic : tree_hash.TreeHashType
| Vector : tree_hash.TreeHashType
| List : tree_hash.TreeHashType
| Container : tree_hash.TreeHashType

/-- Trait declaration: [tree_hash::TreeHash]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tree_hash-0.12.0/src/lib.rs', lines 109:0-109:18
    Name pattern: [tree_hash::TreeHash]
    Visibility: public -/
@[rust_trait "tree_hash::TreeHash"]
structure tree_hash.TreeHash (Self : Type) where
  tree_hash_type : Result tree_hash.TreeHashType
  tree_hash_packed_encoding : Self → Result (smallvec.SmallVec (Array Std.U8
    32#usize) Std.U8)
  tree_hash_packing_factor : Result Std.Usize
  tree_hash_root : Self → Result (alloy_primitives.bits.fixed.FixedBytes
    32#usize)

/-- Trait declaration: [typenum::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.17.0/src/lib.rs', lines 180:4-180:20
    Name pattern: [typenum::sealed::Sealed]
    Visibility: public -/
@[rust_trait "typenum::sealed::Sealed"]
structure typenum.sealed.Sealed (Self : Type) where

/-- Trait declaration: [typenum::marker_traits::Unsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.17.0/src/marker_traits.rs', lines 59:0-59:53
    Name pattern: [typenum::marker_traits::Unsigned]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Unsigned"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "U16", "U32", "U64", "USIZE", "I8", "I16", "I32", "I64", "ISIZE"])]
structure typenum.marker_traits.Unsigned (Self : Type) where
  U8 : Result Std.U8
  U16 : Result Std.U16
  U32 : Result Std.U32
  U64 : Result Std.U64
  USIZE : Result Std.Usize
  I8 : Result Std.I8
  I16 : Result Std.I16
  I32 : Result Std.I32
  I64 : Result Std.I64
  ISIZE : Result Std.Isize
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  to_u8 : Result Std.U8
  to_u16 : Result Std.U16
  to_u32 : Result Std.U32
  to_u64 : Result Std.U64
  to_usize : Result Std.Usize
  to_i8 : Result Std.I8
  to_i16 : Result Std.I16
  to_i32 : Result Std.I32
  to_i64 : Result Std.I64
  to_isize : Result Std.Isize

/-- [milhouse::utils::Length]
    Source: 'src/utils.rs', lines 25:0-25:29
    Visibility: public -/
@[reducible]
def utils.Length := Std.Usize

/-- [milhouse::utils::MaybeArced]
    Source: 'src/utils.rs', lines 8:0-11:1
    Visibility: public -/
@[discriminant isize]
inductive utils.MaybeArced (T : Type) where
| Arced : triomphe.arc.Arc T → utils.MaybeArced T
| Unarced : T → utils.MaybeArced T

/-- [milhouse::packed_leaf::PackedLeaf]
    Source: 'src/packed_leaf.rs', lines 9:0-14:1
    Visibility: public -/
structure packed_leaf.PackedLeaf (T : Type) where
  hash : lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize)
  values : alloc.vec.Vec T

/-- [milhouse::leaf::Leaf]
    Source: 'src/leaf.rs', lines 9:0-15:1
    Visibility: public -/
structure leaf.Leaf (T : Type) where
  hash : lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize)
  value : triomphe.arc.Arc T

/-- [milhouse::tree::Tree]
    Source: 'src/tree.rs', lines 13:0-26:1
    Visibility: public -/
@[discriminant isize]
inductive tree.Tree (T : Type) where
| Leaf : leaf.Leaf T → tree.Tree T
| PackedLeaf : packed_leaf.PackedLeaf T → tree.Tree T
| Node :
  lock_api.rwlock.RwLock parking_lot.raw_rwlock.RawRwLock
    (alloy_primitives.bits.fixed.FixedBytes 32#usize) →
  triomphe.arc.Arc (tree.Tree T) →
  triomphe.arc.Arc (tree.Tree T) →
  tree.Tree T
| Zero : Std.Usize → tree.Tree T

/-- [milhouse::builder::Builder]
    Source: 'src/builder.rs', lines 5:0-18:1
    Visibility: public -/
structure builder.Builder (T : Type) where
  stack : alloc.vec.Vec (utils.MaybeArced (tree.Tree T))
  depth : Std.Usize
  level : Std.Usize
  length : utils.Length
  packing_factor : Option Std.Usize
  packing_depth : Std.Usize
  capacity : Std.Usize

/-- Trait declaration: [milhouse::Value]
    Source: 'src/lib.rs', lines 54:0-54:66
    Visibility: public -/
structure Value (Self : Type) where
  sszencodeEncodeInst : ssz.encode.Encode Self
  sszdecodeDecodeInst : ssz.decode.Decode Self
  tree_hashTreeHashInst : tree_hash.TreeHash Self
  corecmpPartialEqInst : core.cmp.PartialEq Self Self
  corecloneCloneInst : core.clone.Clone Self

/-- [milhouse::error::Error]
    Source: 'src/error.rs', lines 4:0-36:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| OutOfBoundsUpdate : Std.Usize → Std.Usize → error.Error
| OutOfBoundsIterFrom : Std.Usize → Std.Usize → error.Error
| ListFull : Std.Usize → error.Error
| PackedLeafFull : Std.Usize → error.Error
| LeafUpdateMissing : Std.Usize → error.Error
| PackedLeafOutOfBounds : Std.Usize → Std.Usize → error.Error
| NodeUpdatesMissing : Std.Usize → error.Error
| InvalidListUpdate : error.Error
| InvalidVectorUpdate : error.Error
| WrongVectorLength : Std.Usize → Std.Usize → error.Error
| PushNotSupported : error.Error
| UpdateLeafError : error.Error
| UpdateLeavesError : error.Error
| InvalidRebaseNode : error.Error
| InvalidRebaseLeaf : error.Error
| BuilderInvalidDepth : Std.Usize → error.Error
| BuilderExpectedLeaf : error.Error
| BuilderStackEmptyMerge : error.Error
| BuilderStackEmptyMergeLeft : error.Error
| BuilderStackEmptyMergeRight : error.Error
| BuilderStackEmptyFinish : error.Error
| BuilderStackEmptyFinishLeft : error.Error
| BuilderStackEmptyFinishRight : error.Error
| BuilderStackEmptyFinalize : error.Error
| BuilderStackLeftover : error.Error
| BuilderFull : error.Error
| CowMissingEntry : error.Error
| LevelIterPendingUpdates : error.Error
| IntraRebaseZeroHash : error.Error
| IntraRebaseZeroDepth : error.Error
| IntraRebaseRepeatVisit : error.Error

/-- [milhouse::cow::VecCow]
    Source: 'src/cow.rs', lines 91:0-99:1
    Visibility: public -/
@[discriminant isize]
inductive cow.VecCow (T : Type) where
| Immutable : T → Option (vec_map.VacantEntry T) → cow.VecCow T
| Mutable : T → cow.VecCow T

/-- [milhouse::cow::BTreeCow]
    Source: 'src/cow.rs', lines 43:0-51:1
    Visibility: public -/
@[discriminant isize]
inductive cow.BTreeCow (T : Type) where
| Immutable :
  T →
  Option (alloc.collections.btree.map.entry.VacantEntry Std.Usize T Global) →
  cow.BTreeCow T
| Mutable : T → cow.BTreeCow T

/-- [milhouse::cow::Cow]
    Source: 'src/cow.rs', lines 5:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive cow.Cow (T : Type) where
| BTree : cow.BTreeCow T → cow.Cow T
| Vec : cow.VecCow T → cow.Cow T

/-- [milhouse::level_iter::LevelIter]
    Source: 'src/level_iter.rs', lines 8:0-27:1
    Visibility: public -/
structure level_iter.LevelIter (T : Type) where
  stack : alloc.vec.Vec (triomphe.arc.Arc (tree.Tree T))
  index : Std.Usize
  level : Std.Usize
  full_depth : Std.Usize
  packing_factor : Std.Usize
  packing_depth : Std.Usize
  length : utils.Length

/-- [milhouse::iter::Iter]
    Source: 'src/iter.rs', lines 7:0-22:1
    Visibility: public -/
structure iter.Iter (T : Type) where
  stack : alloc.vec.Vec (tree.Tree T)
  index : Std.Usize
  full_depth : Std.Usize
  packing_factor : Std.Usize
  packing_depth : Std.Usize
  length : utils.Length

/-- Trait declaration: [milhouse::interface::ImmList]
    Source: 'src/interface.rs', lines 13:0-25:1
    Visibility: public -/
structure interface.ImmList (Self : Type) (T : Type) where
  ValueInst : Value T
  get : Self → Std.Usize → Result (Option T)
  len : Self → Result utils.Length
  is_empty : Self → Result Bool
  iter_from : Self → Std.Usize → Result (iter.Iter T)
  level_iter_from : Self → Std.Usize → Result (level_iter.LevelIter T)

/-- Trait declaration: [milhouse::update_map::UpdateMap]
    Source: 'src/update_map.rs', lines 9:0-41:1
    Visibility: public -/
structure update_map.UpdateMap (Self : Type) (T : Type) where
  coredefaultDefaultInst : core.default.Default Self
  corecloneCloneInst : core.clone.Clone Self
  get : Self → Std.Usize → Result (Option T)
  get_mut_with : forall {F : Type} (coreopsfunctionFnOncePTupleUsizeOptionInst
    : core.ops.function.FnOnce F Std.Usize (Option T)), Self → Std.Usize →
    F → Result ((Option T) × (Option T → Self))
  get_cow_with : forall {F : Type}
    (coreopsfunctionFnOncePTupleUsizeOptionSharedPInst :
    core.ops.function.FnOnce F Std.Usize (Option T)) (corecloneCloneInst1 :
    core.clone.Clone T), Self → Std.Usize → F → Result ((Option (cow.Cow
    T)) × (Option (cow.Cow T) → Self))
  insert : Self → Std.Usize → T → Result ((Option T) × Self)
  for_each_range : forall {F : Type} {E : Type}
    (coreopsfunctionFnMutPPairUsizeShared0EControlFlowTupleResultTuplePInst :
    core.ops.function.FnMut F (Std.Usize × T)
    (core.ops.control_flow.ControlFlow Unit (core.result.Result Unit E))), Self
    → Std.Usize → Std.Usize → F → Result (core.result.Result Unit E)
  has_any_in_range : Self → Std.Usize → Std.Usize → Result Bool
  max_index : Self → Result (Option Std.Usize)
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool

/-- Trait declaration: [milhouse::interface::MutList]
    Source: 'src/interface.rs', lines 27:0-35:1
    Visibility: public -/
structure interface.MutList (Self : Type) (T : Type) where
  ImmListInst : interface.ImmList Self T
  ValueInst : Value T
  validate_push : Std.Usize → Result (core.result.Result Unit error.Error)
  replace : Self → Std.Usize → T → Result ((core.result.Result Unit
    error.Error) × Self)
  update : forall {U : Type} (update_mapUpdateMapInst : update_map.UpdateMap U
    T), Self → U → Option (alloc.collections.btree.map.BTreeMap (Std.Usize
    × Std.Usize) (alloy_primitives.bits.fixed.FixedBytes 32#usize) Global) →
    Result ((core.result.Result Unit error.Error) × Self)

/-- [milhouse::interface::Interface]
    Source: 'src/interface.rs', lines 39:0-48:1
    Visibility: public -/
structure interface.Interface (T : Type) (B : Type) (U : Type) where
  backing : B
  updates : U
  _phantom : core.marker.PhantomData T

/-- [milhouse::list::ListInner]
    Source: 'src/list.rs', lines 41:0-49:1
    Visibility: public -/
structure list.ListInner (T : Type) (N : Type) where
  tree : triomphe.arc.Arc (tree.Tree T)
  length : utils.Length
  depth : Std.Usize
  packing_depth : Std.Usize
  _phantom : core.marker.PhantomData N

/-- [milhouse::list::List]
    Source: 'src/list.rs', lines 30:0-32:1
    Visibility: public -/
structure list.List (T : Type) (N : Type) (U : Type) where
  interface : interface.Interface T (list.ListInner T N) U

/-- [milhouse::utils::updated_length::closure]
    Source: 'src/utils.rs', lines 87:41-89:5 -/
@[reducible]
def utils.updated_length.closure (U : Type) (T : Type) := utils.Length

/-- [milhouse::tree::RebaseAction]
    Source: 'src/tree.rs', lines 246:0-255:1
    Visibility: public -/
@[discriminant isize]
inductive tree.RebaseAction (T : Type) where
| NotEqualNoop : tree.RebaseAction T
| NotEqualReplace : triomphe.arc.Arc T → tree.RebaseAction T
| EqualNoop : tree.RebaseAction T
| EqualReplace : triomphe.arc.Arc T → tree.RebaseAction T

/-- [milhouse::tree::IntraRebaseAction]
    Source: 'src/tree.rs', lines 257:0-260:1
    Visibility: public -/
@[discriminant isize]
inductive tree.IntraRebaseAction (T : Type) where
| Noop : tree.IntraRebaseAction T
| Replace : triomphe.arc.Arc T → tree.IntraRebaseAction T

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::closure#1]
    Source: 'src/tree.rs', lines 317:25-330:21 -/
@[reducible]
def tree.Tree.rebase_on.closure_1 (T : Type) := Std.Usize

/-- [milhouse::tree::{milhouse::tree::Tree<T>}::rebase_on::closure]
    Source: 'src/tree.rs', lines 310:42-310:97 -/
@[reducible]
def tree.Tree.rebase_on.closure (T : Type) := Unit

end milhouse
